// Sumber belajar gratis per topik. Hasil audit 13 Sep 2026: setiap URL dibuka dan dicatat
// penerbit, tahun terbit atau pembaruan terakhir, serta kategori akreditasi penerbitnya.
// Kategori akreditasi: "universitas terakreditasi", "badan pemerintah", "badan standar",
// "asosiasi industri", "lembaga non-akademik" (kategori terakhir tidak lagi dipakai setelah audit).
// Bentuk: { slug: [ { title, url, kind, description, publisher, year, accreditation } ] }
export const RESOURCES = {
  fund: [
    { title: "Events Industry Council: CMP International Standards (Updated February 2025)", url: "https://news.eventscouncil.org/wp-content/uploads/2025/01/CMP-International-Standards-2025.pdf", kind: "framework", description: "Body of knowledge resmi sertifikasi Certified Meeting Professional (PDF 13 halaman, gratis). Memetakan kompetensi manajer event ke domain A sampai L: perencanaan strategis, keberlanjutan dan dampak sosial, manajemen keuangan, manajemen pemangku kepentingan, desain event, manajemen lokasi, pemasaran dan komunikasi, integrasi teknologi, sampai proses evaluasi.", publisher: "Events Industry Council (EIC)", year: "2025", accreditation: "asosiasi industri" },
    { title: "Introduction to Tourism and Hospitality in BC, 2nd Edition, bab 6.1 Festivals and Events (BCcampus)", url: "https://opentextbc.ca/introtourism2e/chapter/festivals-and-events/", kind: "textbook", description: "Bab buku teks terbuka (CC BY 4.0) tentang definisi festival dan event, tipe event (mega, special, hallmark, festival, community) berdasarkan Getz, dan daftar tugas pokok event planner dari konsep sampai evaluasi.", publisher: "BCcampus Open Publishing (Morgan Westcott dan Wendy Anderson; didanai Pemerintah British Columbia)", year: "2021 (edisi ke-2; hak cipta 2015, 2020, 2021)", accreditation: "badan pemerintah" },
    { title: "Events Industry Council Industry Glossary", url: "https://insights.eventscouncil.org/Industry-glossary", kind: "guide", description: "Glosarium resmi EIC dengan sekitar 1.350 istilah industri event dan MICE, bisa ditelusuri per huruf tanpa login.", publisher: "Events Industry Council (EIC)", year: "tidak tercantum", accreditation: "asosiasi industri" },
  ],
  "pb-lead": [
    { title: "Leadership and followership (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/education-development/learning/leadership-and-followership/content-section-overview", kind: "course", description: "Kursus gratis 24 jam (Level 1) tentang gaya kepemimpinan, membangun tim, memotivasi staf dan mengelola perubahan, dengan badge digital gratis dan 24 poin CPD.", publisher: "The Open University (OpenLearn)", year: "2024 (terbit dan diperbarui 02/01/2024)", accreditation: "universitas terakreditasi" },
    { title: "OpenStax Principles of Management, bab 13: Leadership", url: "https://openstax.org/books/principles-management/pages/13-introduction", kind: "textbook", description: "Bab buku teks gratis (CC BY) tentang proses kepemimpinan, pendekatan sifat, perilaku dan situasional, serta kepemimpinan transformasional versus transaksional. Bab 1 sampai 4 buku yang sama membahas peran manajer dan pengambilan keputusan.", publisher: "OpenStax (Rice University)", year: "2019 (revisi Juni 2026)", accreditation: "universitas terakreditasi" },
  ],
  "pb-speak": [
    { title: "Introduction to Public Speaking (University of Washington, Coursera)", url: "https://www.coursera.org/learn/public-speaking", kind: "course", description: "Kursus lima modul dari University of Washington (pengajar Dr. Matt McGarrity) yang bisa diikuti gratis tanpa sertifikat: struktur pidato, menyusun ide, teknik penyampaian, mengelola gugup, dan latihan presentasi. Berguna untuk MC dan presentasi ke klien.", publisher: "University of Washington (via Coursera, jalur audit gratis)", year: "tidak tercantum", accreditation: "universitas terakreditasi" },
    { title: "Talk the talk (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/education-development/talk-the-talk", kind: "course", description: "Kursus gratis 12 jam tentang presentasi lisan yang persuasif: pembukaan dan penutup, bahasa tubuh dan proyeksi suara, memakai contoh TED Talk.", publisher: "The Open University (OpenLearn)", year: "2019 (diperbarui 19/12/2019; terbit 2015)", accreditation: "universitas terakreditasi" },
  ],
  "pb-english": [
    { title: "British Council LearnEnglish: Business English", url: "https://learnenglish.britishcouncil.org/business-english", kind: "course", description: "Materi gratis British Council untuk bahasa Inggris bisnis: Business magazine, Podcasts for professionals, dan seri English for emails, dengan latihan per level.", publisher: "British Council (badan publik non-departemen Pemerintah Inggris)", year: "tidak tercantum", accreditation: "badan pemerintah" },
    { title: "Effective communication in the workplace (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/money-business/effective-communication-the-workplace", kind: "course", description: "Kursus gratis 24 jam tentang komunikasi verbal, nonverbal dan tertulis di tempat kerja, mendengar aktif, etika email, dan komunikasi lintas budaya, dengan badge digital gratis.", publisher: "The Open University (OpenLearn)", year: "2020 (diperbarui 07/04/2020)", accreditation: "universitas terakreditasi" },
  ],
  bizdev: [
    { title: "Understanding your customers (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/money-business/understanding-your-customers/content-section-0", kind: "course", description: "Kursus gratis 8 jam (Level 2) tentang perbedaan pemasaran konsumen dan B2B serta proses keputusan pembelian organisasi, berguna untuk memahami klien korporat.", publisher: "The Open University (OpenLearn)", year: "2020 (terbit dan diperbarui 06/11/2020)", accreditation: "universitas terakreditasi" },
    { title: "OpenStax Principles of Marketing, 15.1 Personal Selling and Its Role in the Promotion Mix", url: "https://openstax.org/books/principles-marketing/pages/15-1-personal-selling-and-its-role-in-the-promotion-mix", kind: "textbook", description: "Bab buku teks gratis tentang personal selling dan relationship selling; bagian 15.3 di bab yang sama menguraikan tahap proses penjualan dari prospecting, pendekatan, presentasi, menangani keberatan, closing, sampai follow-up.", publisher: "OpenStax (Rice University)", year: "2023 (revisi April 2026)", accreditation: "universitas terakreditasi" },
  ],
  pm: [
    { title: "PM² Project Management Methodology Guide 3.1 (European Commission)", url: "https://op.europa.eu/en/publication-detail/-/publication/97cc2f12-c648-11ee-95d9-01aa75ed71a1", kind: "guide", description: "Panduan metodologi manajemen proyek resmi Komisi Eropa (PDF gratis, CC BY 4.0, tersedia dalam beberapa bahasa): siklus hidup proyek dari initiating sampai closing, tata kelola dan peran, artefak seperti business case, project charter dan project work plan, serta pemantauan dan pengendalian.", publisher: "European Commission, Directorate-General for Digital Services (Publications Office of the European Union)", year: "2023 (edisi 3.1; dimuat di Publications Office Februari 2024)", accreditation: "badan pemerintah" },
    { title: "ISO 21502:2020 Project, programme and portfolio management, Guidance on project management (halaman resmi ISO)", url: "https://www.iso.org/standard/74947.html", kind: "standard", description: "Ringkasan resmi ISO (gratis, ada 'Read sample') tentang panduan praktik manajemen proyek untuk organisasi apa pun, termasuk pendekatan prediktif, iteratif dan agile; teks standar lengkap berbayar.", publisher: "International Organization for Standardization (ISO)", year: "2020", accreditation: "badan standar" },
  ],
  concept: [
    { title: "OpenStax Entrepreneurship, bab 4: Creativity, Innovation, and Invention", url: "https://openstax.org/books/entrepreneurship/pages/4-introduction", kind: "textbook", description: "Bab buku teks gratis tentang alat untuk kreativitas dan inovasi, perbedaan kreativitas, inovasi dan invensi, serta cara mengembangkan ide menjadi konsep yang bisa diuji. Cocok sebagai dasar merancang konsep event.", publisher: "OpenStax (Rice University)", year: "2020 (revisi Juni 2026)", accreditation: "universitas terakreditasi" },
    { title: "Design thinking (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/science-maths-technology/design-innovation/design-thinking/", kind: "course", description: "Kursus gratis 10 jam untuk menstrukturkan kreativitas: prinsip desain, berpikir visual, komposisi, dan cara menjelaskan keputusan desain.", publisher: "The Open University (OpenLearn)", year: "2018 (diperbarui 05/12/2018; terbit 2012)", accreditation: "universitas terakreditasi" },
    { title: "Making creativity and innovation happen (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/money-business/making-creativity-and-innovation-happen/content-section-0", kind: "course", description: "Kursus gratis 10 jam (Level 2) tentang kreativitas individu dan organisasi serta budaya, kepemimpinan dan praktik yang mendukung ide baru.", publisher: "The Open University (OpenLearn)", year: "2019 (diperbarui 15/08/2019)", accreditation: "universitas terakreditasi" },
  ],
  proposal: [
    { title: "HSE Event safety: Getting started", url: "https://www.hse.gov.uk/event-safety/getting-started.htm", kind: "guide", description: "Panduan resmi HSE Inggris tentang langkah awal merencanakan event: struktur tanggung jawab, rencana keselamatan, memilih kontraktor, koordinasi dengan venue dan layanan darurat, plus checklist perencanaan.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2024 (diperbarui 11/10/2024)", accreditation: "badan pemerintah" },
    { title: "University of Exeter Event Toolkit: Planning an event", url: "https://www.exeter.ac.uk/departments/communication/communications/events/toolkit/planning-event/", kind: "university", description: "Toolkit universitas berisi tahapan perencanaan event dari tujuan, anggaran, timeline sampai checklist, template agenda dan formulir pembicara, serta panduan aksesibilitas.", publisher: "University of Exeter, Marketing, Student Recruitment and Communications", year: "tidak tercantum", accreditation: "universitas terakreditasi" },
    { title: "Thurrock Council: Event Management Plan (EMP) template", url: "https://www.thurrock.gov.uk/sites/default/files/assets/documents/event-management-plan-v01.pdf", kind: "guide", description: "Template EMP 30 halaman dari pemerintah daerah Inggris dengan catatan panduan tiap bagian, untuk event kecil di bawah 500 orang sampai festival di atas 10.000 orang, termasuk tenggat pengajuan ke Safety Advisory Group.", publisher: "Thurrock Council (pemerintah daerah, Inggris)", year: "2022 (metadata PDF April 2022)", accreditation: "badan pemerintah" },
  ],
  bizplan: [
    { title: "U.S. SBA: Write your business plan", url: "https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan", kind: "guide", description: "Panduan pemerintah AS tentang format business plan tradisional dan lean startup, sembilan bagian bakunya, plus contoh unduhan dan kalkulator break-even.", publisher: "U.S. Small Business Administration (SBA)", year: "tidak tercantum", accreditation: "badan pemerintah" },
    { title: "OpenStax Entrepreneurship, bab 11: Business Model and Plan", url: "https://openstax.org/books/entrepreneurship/pages/11-introduction", kind: "textbook", description: "Bab buku teks gratis tentang merancang model bisnis, analisis kelayakan, dan menyusun business plan yang berfokus pada pelanggan.", publisher: "OpenStax (Rice University)", year: "2020 (revisi Juni 2026)", accreditation: "universitas terakreditasi" },
    { title: "business.gov.au: Develop your business plan", url: "https://business.gov.au/planning/business-plans/develop-your-business-plan", kind: "guide", description: "Panduan Pemerintah Australia untuk menyusun rencana bisnis, dengan template business plan (DOCX) gratis dan alat perencanaan daring sederhana, termasuk tips menyiapkan bagian keuangan dan ringkasan eksekutif.", publisher: "Pemerintah Australia (business.gov.au)", year: "tidak tercantum", accreditation: "badan pemerintah" },
  ],
  bud: [
    { title: "OpenStax Principles of Accounting Vol. 2, 7.1 Describe How and Why Managers Use Budgets", url: "https://openstax.org/books/principles-managerial-accounting/pages/7-1-describe-how-and-why-managers-use-budgets", kind: "textbook", description: "Awal bab budgeting buku teks gratis: fungsi anggaran, pendekatan top-down, bottom-up dan zero-based, anggaran statis dan fleksibel, serta master budget.", publisher: "OpenStax (Rice University)", year: "2019", accreditation: "universitas terakreditasi" },
    { title: "Imperial College Union eActivities: Event Finances", url: "https://eactivities.union.ic.ac.uk/training/finance/events", kind: "university", description: "Materi pelatihan tentang anggaran event yang layak: estimasi peserta konservatif, break even, arus kas negatif sementara, dan persetujuan anggaran sebelum kontrak ditandatangani.", publisher: "Imperial College Union (Imperial College London)", year: "tidak tercantum (hak cipta situs 2026)", accreditation: "universitas terakreditasi" },
    { title: "University of Exeter Event Toolkit: Budget and costing events", url: "https://www.exeter.ac.uk/departments/communication/communications/events/toolkit/budget-costing/", kind: "university", description: "Cara menyusun anggaran dan menghitung biaya event, termasuk template anggaran untuk konferensi dan workshop, pengajuan dana, dan pengendalian pengeluaran lewat purchase order.", publisher: "University of Exeter, Marketing, Student Recruitment and Communications", year: "tidak tercantum", accreditation: "universitas terakreditasi" },
  ],
  team: [
    { title: "Working in groups and teams (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/money-business/leadership-management/working-groups-and-teams/content-section-0", kind: "course", description: "Kursus gratis 8 jam (Level 3) tentang peran dalam tim, tahap perkembangan tim, mengelola konflik, dan mengevaluasi kinerja tim.", publisher: "The Open University (OpenLearn)", year: "2019 (diperbarui 12/06/2019)", accreditation: "universitas terakreditasi" },
    { title: "Working in the voluntary sector (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/society-politics-law/sociology/working-the-voluntary-sector/content-section-overview", kind: "course", description: "Kursus gratis 24 jam yang di minggu ke-2 khusus membahas merekrut, melatih, memotivasi, dan mempertahankan relawan.", publisher: "The Open University (OpenLearn)", year: "2020 (diperbarui 09/01/2020)", accreditation: "universitas terakreditasi" },
    { title: "HSE Event safety: roles at events", url: "https://www.hse.gov.uk/event-safety/roles.htm", kind: "guide", description: "Tanggung jawab tiap peran di event: organiser, kontraktor, pemilik venue, supervisor, pekerja, relawan, dan organisasi sukarela. Berguna untuk briefing dan pembagian peran kru.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2023 (diperbarui 16/03/2023)", accreditation: "badan pemerintah" },
  ],
  mkt: [
    { title: "Marketing communications in the digital age (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/money-business/marketing/marketing-communications-the-digital-age/content-section-0", kind: "course", description: "Kursus gratis 12 jam (Level 2) tentang model komunikasi pemasaran, desain pesan, etika, dan alat digital termasuk media sosial, email, dan online PR.", publisher: "The Open University (OpenLearn)", year: "2026 (diperbarui 03/03/2026; terbit 2022)", accreditation: "universitas terakreditasi" },
    { title: "OpenStax Principles of Marketing", url: "https://openstax.org/books/principles-marketing/pages/1-1-marketing-and-the-marketing-process", kind: "textbook", description: "Buku teks pemasaran gratis yang bisa dibaca per bab, termasuk bab 13 komunikasi pemasaran terpadu, bab 14 iklan dan PR, dan bab 16 direct, online, social media, dan mobile marketing.", publisher: "OpenStax (Rice University)", year: "2023 (revisi April 2026)", accreditation: "universitas terakreditasi" },
    { title: "NSW Government Event Starter Guide: Finding sponsors for your event", url: "https://www.nsw.gov.au/departments-and-agencies/premiers-department/community-engagement/event-starter-guide/sponsorship", kind: "guide", description: "Panduan pemerintah negara bagian NSW tentang mencari sponsor event: riset calon sponsor yang selaras dengan nilai event, bertemu langsung, menyusun proposal yang disesuaikan dengan tujuan bisnis sponsor, paket sponsor bertingkat, perjanjian tertulis, dan menjaga hubungan sponsor.", publisher: "NSW Government, Premier's Department (Australia)", year: "tidak tercantum", accreditation: "badan pemerintah" },
  ],
  tech: [
    { title: "An Introduction to Technical Theatre (Tal Sanders, Open Textbook Library)", url: "https://open.umn.edu/opentextbooks/textbooks/an-introduction-to-technical-theatre", kind: "textbook", description: "Buku teks terbuka (CC BY-NC) 15 modul tentang ruang panggung, peralatan, scenery, lighting, sound, stage management, dan etika kru, dengan penekanan keselamatan.", publisher: "Pacific University Press (dimuat di Open Textbook Library, Open Education Network, University of Minnesota)", year: "2018", accreditation: "universitas terakreditasi" },
    { title: "Technical Theatre Practicum (Boltz), 1.7 Stage Lighting (LibreTexts)", url: "https://human.libretexts.org/Bookshelves/Theater_Film_and_Storytelling/Technical_Theatre_Practicum_(Boltz)/01:_Chapters/1.07:_Stage_Lighting", kind: "textbook", description: "Bab singkat (CC BY 4.0) tentang dasar tata cahaya panggung: membaca light plot, pemasangan dan focusing, serta sesi cueing; bab 1.9 di buku yang sama membahas dasar tata suara.", publisher: "Humanities LibreTexts (proyek OER berbasis University of California, Davis); penulis Christopher R. Boltz", year: "2020 (diperbarui 29/07/2020)", accreditation: "universitas terakreditasi" },
    { title: "HSE Event safety: Temporary demountable structures", url: "https://www.hse.gov.uk/event-safety/temporary-demountable-structures.htm", kind: "guide", description: "Panduan keselamatan pemasangan dan pembongkaran struktur sementara (panggung, tower speaker, lighting) serta pemilihan peralatan penopangnya.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2023 (diperbarui 16/03/2023)", accreditation: "badan pemerintah" },
  ],
  prodplan: [
    { title: "HSE Event safety: Managing an event", url: "https://www.hse.gov.uk/event-safety/managing-an-event.htm", kind: "guide", description: "Mengelola keselamatan selama build-up, load-in, breakdown, dan load-out: koordinasi kontraktor, briefing kru, pemantauan, dan debrief.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2024 (diperbarui 12/10/2024)", accreditation: "badan pemerintah" },
    { title: "HSE Event safety: Transport", url: "https://www.hse.gov.uk/event-safety/transport.htm", kind: "guide", description: "Pengelolaan lalu lintas kendaraan dan pejalan kaki di lokasi event, termasuk pergerakan kendaraan produksi saat load in dan load out serta koordinasi penutupan jalan.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2025 (diperbarui 04/09/2025)", accreditation: "badan pemerintah" },
    { title: "Brighton Council (Tasmania): Event Management Kit, 8 July 2025", url: "https://www.brighton.tas.gov.au/wp-content/uploads/2025/07/FINAL-Event-Management-Kit-8-July-25.pdf", kind: "guide", description: "Kit 35 halaman dari pemerintah daerah Australia untuk penyelenggara event, termasuk bagian Program Schedule/Run Sheet yang menjelaskan isi running sheet (bump in, jadwal acara, bump out) dan checklist dokumen yang wajib disiapkan.", publisher: "Brighton Council (pemerintah daerah, Tasmania, Australia)", year: "2025", accreditation: "badan pemerintah" },
  ],
  venue: [
    { title: "HSE Event safety: Venue and site design", url: "https://www.hse.gov.uk/event-safety/venue-site-design.htm", kind: "guide", description: "Menilai kapasitas venue, kondisi tanah dan struktur, akses kendaraan dan pejalan kaki, serta menyusun site plan (struktur, fasilitas, pagar, pintu masuk dan keluar).", publisher: "Health and Safety Executive (HSE), Inggris", year: "2024 (diperbarui 12/10/2024)", accreditation: "badan pemerintah" },
    { title: "University of Exeter Event Toolkit: Booking facilities", url: "https://www.exeter.ac.uk/departments/communication/communications/events/toolkit/booking-facilities/", kind: "university", description: "Contoh alur memesan ruang, katering, peralatan audiovisual, parkir dan keamanan untuk event, termasuk rekomendasi venue dan perkiraan tarif delegasi.", publisher: "University of Exeter, Marketing, Student Recruitment and Communications", year: "tidak tercantum", accreditation: "universitas terakreditasi" },
    { title: "City of Sydney: Venue Hire Agreement (community venues, not staffed)", url: "https://www.cityofsydney.nsw.gov.au/-/media/corporate/files/places-and-spaces/community-centres/conditions-of-hire/booking-confirmation-and-special-conditions-venues-unstaffed.pdf?download=true", kind: "guide", description: "Contoh nyata kontrak sewa venue dari pemerintah kota: syarat pemesanan, deposit, kewajiban penyewa, hak inspeksi, dan kondisi khusus.", publisher: "City of Sydney (pemerintah kota, Australia)", year: "2021 (metadata PDF Maret 2021)", accreditation: "badan pemerintah" },
  ],
  reg: [
    { title: "STAR (Society of Ticket Agents and Retailers) Code of Practice", url: "https://www.star.org.uk/wp-content/uploads/STAR-Code-Of-Practice.pdf", kind: "standard", description: "Kode praktik industri tiket Inggris yang masih berlaku: transparansi harga, refund bila event batal, syarat tiket, penanganan uang pelanggan, dan komplain. STAR adalah badan swa-regulasi tiket yang disetujui pemerintah Inggris sebagai badan ADR konsumen.", publisher: "Society of Ticket Agents and Retailers (STAR)", year: "2017 (Updated June 2017; belum ada edisi baru per Sep 2026)", accreditation: "asosiasi industri" },
    { title: "NSW Government: Toolkit for Accessible and Inclusive Events", url: "https://www.nsw.gov.au/sites/default/files/2023-07/Toolkit-for-Accessible-and-Inclusive-Events.pdf", kind: "guide", description: "Checklist, simbol aksesibilitas, panduan bahasa inklusif, dan contoh formulir registrasi aksesibilitas agar pendaftaran dan check-in inklusif.", publisher: "NSW Government, Premier's Department (Australia)", year: "2026 (edisi Juli 2026)", accreditation: "badan pemerintah" },
    { title: "University of Exeter Event Toolkit: Eventbrite, event marketing and publicity", url: "https://www.exeter.ac.uk/departments/communication/communications/events/toolkit/eventbriteeventmarketingandpublicity/", kind: "university", description: "Memakai Eventbrite atau Microsoft Forms untuk registrasi peserta, memilih toko daring untuk tiket berbayar, dan menggabungkannya dengan promosi event; ada panduan Eventbrite yang bisa diunduh.", publisher: "University of Exeter, Marketing, Student Recruitment and Communications", year: "2024 (panduan Eventbrite tertanggal September 2024)", accreditation: "universitas terakreditasi" },
  ],
  risk: [
    { title: "ISO 31000:2018 Risk management, Guidelines (halaman resmi ISO)", url: "https://www.iso.org/standard/65694.html", kind: "standard", description: "Ringkasan resmi ISO (gratis, ada 'Read sample') tentang prinsip, kerangka, dan proses manajemen risiko; teks standar lengkap berbayar.", publisher: "International Organization for Standardization (ISO)", year: "2018", accreditation: "badan standar" },
    { title: "HSE: Managing risks and risk assessment at work", url: "https://www.hse.gov.uk/simple-health-safety/risk/index.htm", kind: "guide", description: "Langkah demi langkah menyusun risk assessment (identifikasi bahaya, nilai risiko, kendali) lengkap dengan template dan contoh.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2025 (diperbarui 24/03/2025)", accreditation: "badan pemerintah" },
    { title: "HSE Event safety: Planning for incidents and emergencies", url: "https://www.hse.gov.uk/event-safety/incidents-and-emergencies.htm", kind: "guide", description: "Menyusun emergency plan event: evakuasi, show stop, koordinasi dengan polisi dan ambulans, uji table-top, dan rencana kontingensi.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2026 (diperbarui 20/01/2026)", accreditation: "badan pemerintah" },
  ],
  bizdoc: [
    { title: "OpenStax Business Law I Essentials, bab 7: Contract Law", url: "https://openstax.org/books/business-law-i-essentials/pages/7-introduction", kind: "textbook", description: "Unsur kontrak yang sah (kesepakatan, consideration, kapasitas, legalitas), pelanggaran dan pemulihannya, dasar untuk memahami kontrak klien dan vendor.", publisher: "OpenStax (Rice University)", year: "2019 (revisi Juni 2026)", accreditation: "universitas terakreditasi" },
    { title: "business.gov.au: Prepare a contract", url: "https://business.gov.au/legal/contracts-and-tenders/prepare-a-contract", kind: "guide", description: "Panduan Pemerintah Australia tentang 14 unsur yang perlu ada dalam kontrak kerja sama: pihak, lingkup pekerjaan, pembayaran, kekayaan intelektual, kerahasiaan, asuransi, subkontrak, penyelesaian sengketa, variasi, dan pengakhiran, dengan contoh dan saran bahasa sederhana.", publisher: "Pemerintah Australia (business.gov.au)", year: "tidak tercantum", accreditation: "badan pemerintah" },
    { title: "Australian Government Style Manual", url: "https://www.stylemanual.gov.au/", kind: "guide", description: "Standar resmi penulisan dan penyuntingan Pemerintah Australia: bahasa yang jelas, struktur dokumen (judul, daftar, tabel), tipe konten seperti laporan, formulir dan email, serta cara mengutip sumber. Rujukan untuk menyusun SOP, laporan, dan dokumen kerja lain yang mudah dipahami.", publisher: "Pemerintah Australia (stylemanual.gov.au)", year: "tidak tercantum (edisi daring, ada changelog)", accreditation: "badan pemerintah" },
  ],
  prod: [
    { title: "CCSU Theatre: Stage Management and Assistant Stage Management Handbook (2023)", url: "https://www.ccsu.edu/sites/default/files/2024-06/SM%20and%20ASM%20Handbook.pdf", kind: "university", description: "Buku pegangan yang merunut kerja stage manager dari pra-produksi, rehearsal, tech rehearsal, calling cues, show run, sampai strike dan laporan pasca-show.", publisher: "Central Connecticut State University, Theatre Department", year: "2023 (PDF dimuat Juni 2024)", accreditation: "universitas terakreditasi" },
    { title: "Technical Theatre Practicum (Boltz), 1.11 Production Reports (LibreTexts)", url: "https://human.libretexts.org/Bookshelves/Theater_Film_and_Storytelling/Technical_Theatre_Practicum_(Boltz)/01:_Chapters/1.11:_Production_Reports", kind: "textbook", description: "Laporan produksi (rehearsal report dan performance report) yang disusun per departemen sebagai bagian dari dokumen produksi.", publisher: "Humanities LibreTexts (proyek OER berbasis University of California, Davis); penulis Christopher R. Boltz", year: "2020 (diperbarui 29/07/2020)", accreditation: "universitas terakreditasi" },
    { title: "Theatre UCF Stage Management Handbook (Last Revised August 2021)", url: "https://cah.ucf.edu/performingarts/wp-content/uploads/sites/46/2020/10/Stage-Management-Handbook-2021.pdf", kind: "university", description: "Buku pegangan 51 halaman program BFA Stage Management University of Central Florida: kalender produksi, jadwal rehearsal dan tech, isi prompt book dan calling script, serta prosedur dan dokumen yang wajib dijaga stage manager.", publisher: "Theatre UCF, University of Central Florida", year: "2021", accreditation: "universitas terakreditasi" },
  ],
  show: [
    { title: "Technical Theatre Practicum (Boltz), 1.12 Cueing Scripts (LibreTexts)", url: "https://human.libretexts.org/Bookshelves/Theater_Film_and_Storytelling/Technical_Theatre_Practicum_(Boltz)/01:_Chapters/1.12:_Cueing_Scripts", kind: "textbook", description: "Cara memanggil cue: warning, standby, go, penomoran cue lampu (LQ) dan suara (SQ), dan menandai naskah untuk cueing.", publisher: "Humanities LibreTexts (proyek OER berbasis University of California, Davis); penulis Christopher R. Boltz", year: "2020 (diperbarui 23/05/2020)", accreditation: "universitas terakreditasi" },
    { title: "CCSU Theatre: Stage Management Handbook (bagian Calling Cues dan Show Run)", url: "https://www.ccsu.edu/sites/default/files/2024-06/SM%20and%20ASM%20Handbook.pdf", kind: "university", description: "Bagian Calling Cues, Pre-Performance/Run Routine, dan Show Run menjelaskan prosedur show calling dan penanganan insiden saat pertunjukan.", publisher: "Central Connecticut State University, Theatre Department", year: "2023 (PDF dimuat Juni 2024)", accreditation: "universitas terakreditasi" },
  ],
  crowd: [
    { title: "HSE Event safety: Crowd management", url: "https://www.hse.gov.uk/event-safety/crowd-management.htm", kind: "guide", description: "Struktur organisasi, penilaian risiko kerumunan, kendali fisik dan prosedural, pemantauan aktif, dan keselamatan area panggung (stage barrier).", publisher: "Health and Safety Executive (HSE), Inggris", year: "2023 (diperbarui 16/03/2023)", accreditation: "badan pemerintah" },
    { title: "Home Office: Terrorism (Protection of Premises) Act 2025 (Martyn's Law), statutory guidance", url: "https://www.gov.uk/government/publications/the-terrorism-protection-of-premises-act-2025", kind: "guide", description: "Panduan statutori Kementerian Dalam Negeri Inggris untuk penanggung jawab tempat dan event berkapasitas 200 orang ke atas (standard duty) dan 800 ke atas (enhanced duty): menilai cakupan, prosedur perlindungan publik saat serangan, dan dokumen pendukung tentang cara memperkirakan jumlah orang yang hadir.", publisher: "Home Office (Pemerintah Inggris)", year: "2026 (terbit 15 April 2026; diperbarui 25 Agustus 2026)", accreditation: "badan pemerintah" },
    { title: "ANZCTC: Australia's Strategy for Protecting Crowded Places from Terrorism (2023)", url: "https://www.nationalsecurity.gov.au/crowded-places-subsite/Files/australias-strategy-protecting-crowded-places-terrorism.pdf", kind: "guide", description: "Strategi resmi Pemerintah Australia (PDF 24 halaman) untuk pemilik dan penyelenggara tempat ramai termasuk event: prinsip kemitraan dengan polisi, penilaian risiko, langkah mitigasi proporsional, dan rujukan ke alat self-assessment dan security audit crowded places.", publisher: "Australia-New Zealand Counter-Terrorism Committee (Commonwealth of Australia)", year: "2023", accreditation: "badan pemerintah" },
  ],
  eval: [
    { title: "eventIMPACTS (UK Sport, EventScotland, Welsh Government, Tourism NI)", url: "https://www.eventimpacts.com/", kind: "guide", description: "Toolkit evaluasi event: cara mengukur attendance, dampak ekonomi (ada kalkulator), sosial, lingkungan, dan media, plus contoh survei dan studi kasus event 2022 sampai 2023.", publisher: "UK Sport, EventScotland, Welsh Government, dan Tourism Northern Ireland", year: "tidak tercantum", accreditation: "badan pemerintah" },
    { title: "ISO 20121:2024 Event sustainability management systems (halaman resmi ISO)", url: "https://www.iso.org/standard/86389.html", kind: "standard", description: "Ringkasan resmi ISO edisi 2024 tentang sistem manajemen keberlanjutan event; teks standar berbayar.", publisher: "International Organization for Standardization (ISO)", year: "2024", accreditation: "badan standar" },
    { title: "Events Industry Council: Sustainable Event Standards", url: "https://insights.eventscouncil.org/Sustainability/Sustainability-Events-Standards", kind: "standard", description: "Ringkasan delapan standar EIC dengan kriteria dan level Foundations, Bronze, Silver, Gold, Platinum yang bisa dijadikan KPI laporan pasca-event.", publisher: "Events Industry Council (EIC)", year: "tidak tercantum (halaman menampilkan data per Agustus 2026)", accreditation: "asosiasi industri" },
  ],
  legal: [
    { title: "GOV.UK: The can-do guide to organising and running voluntary and community events", url: "https://www.gov.uk/government/publications/can-do-guide-for-organisers-of-voluntary-events/the-can-do-guide-to-organising-and-running-voluntary-and-community-events", kind: "guide", description: "Panduan ringkas tentang izin dan lisensi, keselamatan, keamanan pangan, asuransi public liability, dan penutupan jalan.", publisher: "Cabinet Office (Pemerintah Inggris)", year: "2019 (diperbarui 25 Februari 2019)", accreditation: "badan pemerintah" },
    { title: "PRS for Music: Live music and events licence", url: "https://www.prsformusic.com/licences/live-performances", kind: "guide", description: "Penjelasan lembaga royalti Inggris tentang lisensi musik untuk festival, konser, dan event komunitas.", publisher: "PRS for Music (lembaga manajemen kolektif hak cipta musik Inggris)", year: "tidak tercantum", accreditation: "asosiasi industri" },
    { title: "SELMI (LMK di bawah LMKN): Public Performance License", url: "https://selmi.or.id/en/music-licensing/public-performance-license/", kind: "guide", description: "Penjelasan lembaga manajemen kolektif Indonesia (didelegasikan LMKN, dibentuk berdasarkan UU Hak Cipta) tentang lisensi pertunjukan publik musik untuk konser, konferensi, pameran, dan bazar.", publisher: "SELMI (Sentra Lisensi Musik Indonesia), LMK di bawah LMKN", year: "2024 (halaman terbit 16 April 2024)", accreditation: "asosiasi industri" },
  ],
};
