// Sumber belajar gratis per topik. Hasil audit ulang 13 Sep 2026 dengan aturan baru pemilik:
// setiap sumber harus terbit atau diperbarui pada 2020 sampai 2026, dan tahun yang memenuhi
// syarat ditulis PALING DEPAN di kolom `year`, diikuti bukti yang dipakai (baris "Updated" di
// halaman, metadata halaman dateModified/dcterms.date, metadata PDF, header HTTP Last-Modified,
// atau metadata revisi buku OpenStax dari API CMS openstax.org).
// Pengecualian tunggal: standar formal yang masih berlaku dan belum punya edisi baru boleh tetap
// dipakai walau terbit sebelum 2020. Entri seperti itu memakai kind "standard", tahun aslinya tetap
// ditulis paling depan, dan diberi kolom tambahan `exempt: "standar yang masih berlaku"`.
// Kategori akreditasi: "universitas terakreditasi", "badan pemerintah", "badan standar",
// "asosiasi industri".
// Bentuk: { slug: [ { title, url, kind, description, publisher, year, accreditation, exempt? } ] }
export const RESOURCES = {
  fund: [
    { title: "Events Industry Council: CMP International Standards (Updated February 2025)", url: "https://news.eventscouncil.org/wp-content/uploads/2025/01/CMP-International-Standards-2025.pdf", kind: "framework", description: "Body of knowledge resmi sertifikasi Certified Meeting Professional (PDF 13 halaman, gratis). Memetakan kompetensi manajer event ke domain A sampai L: perencanaan strategis, keberlanjutan dan dampak sosial, manajemen keuangan, manajemen pemangku kepentingan, desain event, manajemen lokasi, pemasaran dan komunikasi, integrasi teknologi, sampai proses evaluasi.", publisher: "Events Industry Council (EIC)", year: "2025 (edisi Februari 2025)", accreditation: "asosiasi industri" },
    { title: "Introduction to Tourism and Hospitality in BC, 2nd Edition, bab 6.1 Festivals and Events (BCcampus)", url: "https://opentextbc.ca/introtourism2e/chapter/festivals-and-events/", kind: "textbook", description: "Bab buku teks terbuka (CC BY 4.0) tentang definisi festival dan event, tipe event (mega, special, hallmark, festival, community) berdasarkan Getz, dan daftar tugas pokok event planner dari konsep sampai evaluasi.", publisher: "BCcampus Open Publishing (Morgan Westcott dan Wendy Anderson; didanai Pemerintah British Columbia)", year: "2021 (edisi ke-2; hak cipta 2015, 2020, 2021)", accreditation: "badan pemerintah" },
    { title: "ISO 22379:2022 Security and resilience, Guidelines for hosting and organizing citywide or regional events (halaman resmi ISO)", url: "https://www.iso.org/standard/50281.html", kind: "standard", description: "Ringkasan resmi ISO (gratis, ada 'Read sample') tentang prinsip menjadi tuan rumah dan penyelenggara event skala kota atau wilayah: kerja sama tuan rumah dan penyelenggara, pelibatan pemangku kepentingan, dampak ekonomi, lingkungan dan sosial, pengelolaan risiko, layanan publik selama event, dan rencana warisan (legacy) event. Teks standar lengkap berbayar.", publisher: "International Organization for Standardization (ISO)", year: "2022 (terbit September 2022, edisi 1; status Published, stage 60.60 per halaman ISO)", accreditation: "badan standar" },
  ],
  "pb-lead": [
    { title: "Leadership and followership (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/education-development/learning/leadership-and-followership/content-section-overview", kind: "course", description: "Kursus gratis 24 jam (Level 1) tentang gaya kepemimpinan, membangun tim, memotivasi staf dan mengelola perubahan, dengan badge digital gratis dan 24 poin CPD.", publisher: "The Open University (OpenLearn)", year: "2024 (terbit dan diperbarui 02/01/2024)", accreditation: "universitas terakreditasi" },
    { title: "OpenStax Principles of Management, bab 13: Leadership", url: "https://openstax.org/books/principles-management/pages/13-introduction", kind: "textbook", description: "Bab buku teks gratis (CC BY) tentang proses kepemimpinan, pendekatan sifat, perilaku dan situasional, serta kepemimpinan transformasional versus transaksional. Bab 1 sampai 4 buku yang sama membahas peran manajer dan pengambilan keputusan.", publisher: "OpenStax (Rice University)", year: "2026 (revisi web 27 Mei 2026 per metadata buku OpenStax; terbit 2019)", accreditation: "universitas terakreditasi" },
  ],
  "pb-speak": [
    { title: "Exploring Public Speaking, 3rd Edition (Barton dan Tucker), Social Sci LibreTexts", url: "https://socialsci.libretexts.org/Bookshelves/Communication/Public_Speaking/Exploring_Public_Speaking_(Barton_and_Tucker)", kind: "textbook", description: "Buku teks terbuka (CC BY-NC-SA 4.0) 16 bab tentang berbicara di depan umum: mengatasi gugup, analisis audiens, etika, riset, menyusun kerangka pidato, teknik penyampaian, alat bantu visual, pilihan bahasa, serta pidato informatif, persuasif dan seremonial. Berguna untuk MC dan presentasi ke klien.", publisher: "Social Sci LibreTexts (proyek OER berbasis University of California, Davis); penulis Kris Barton dan Barbara G. Tucker, sumber asli GALILEO Open Learning Materials (University System of Georgia)", year: "2026 (metadata halaman article:modified_time 12/08/2026; dimuat di LibreTexts 2019)", accreditation: "universitas terakreditasi" },
    { title: "Public Speaking (The Public Speaking Project), Social Sci LibreTexts", url: "https://socialsci.libretexts.org/Bookshelves/Communication/Public_Speaking/Public_Speaking_(The_Public_Speaking_Project)", kind: "textbook", description: "Buku teks terbuka (CC BY-NC-ND 3.0) 18 bab: dasar berbicara di depan umum, membangun rasa percaya diri, mendengarkan, analisis audiens, penyampaian, bahasa, alat bantu visual, pidato informatif dan persuasif, presentasi kelompok, serta berbicara untuk audiens global.", publisher: "Social Sci LibreTexts (proyek OER berbasis University of California, Davis); penulis Lisa Schreiber dan Morgan Hartranft", year: "2024 (metadata halaman article:modified_time 16/09/2024; dimuat di LibreTexts 2018)", accreditation: "universitas terakreditasi" },
  ],
  "pb-english": [
    { title: "Everyday English 2 (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/languages/everyday-english-2/content-section-overview", kind: "course", description: "Kursus gratis 48 jam (Level 1, dengan badge digital) setara Functional Skills English Level 2: berbicara dan mendengar (bahasa formal dan informal, komunikasi nonverbal, diskusi, presentasi), membaca (skimming, scanning, fakta versus opini, laporan), dan menulis (perencanaan, draf, proofreading, email, surat, laporan, artikel).", publisher: "The Open University (OpenLearn)", year: "2020 (diperbarui 20/01/2020; terbit 18/04/2019)", accreditation: "universitas terakreditasi" },
    { title: "Effective communication in the workplace (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/money-business/effective-communication-the-workplace", kind: "course", description: "Kursus gratis 24 jam tentang komunikasi verbal, nonverbal dan tertulis di tempat kerja, mendengar aktif, etika email, dan komunikasi lintas budaya, dengan badge digital gratis.", publisher: "The Open University (OpenLearn)", year: "2020 (diperbarui 07/04/2020)", accreditation: "universitas terakreditasi" },
  ],
  bizdev: [
    { title: "Understanding your customers (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/money-business/understanding-your-customers/content-section-0", kind: "course", description: "Kursus gratis 8 jam (Level 2) tentang perbedaan pemasaran konsumen dan B2B serta proses keputusan pembelian organisasi, berguna untuk memahami klien korporat.", publisher: "The Open University (OpenLearn)", year: "2020 (terbit dan diperbarui 06/11/2020)", accreditation: "universitas terakreditasi" },
    { title: "OpenStax Principles of Marketing, 15.1 Personal Selling and Its Role in the Promotion Mix", url: "https://openstax.org/books/principles-marketing/pages/15-1-personal-selling-and-its-role-in-the-promotion-mix", kind: "textbook", description: "Bab buku teks gratis tentang personal selling dan relationship selling; bagian 15.3 di bab yang sama menguraikan tahap proses penjualan dari prospecting, pendekatan, presentasi, menangani keberatan, closing, sampai follow-up.", publisher: "OpenStax (Rice University)", year: "2026 (revisi web 18 Agustus 2026 per metadata buku OpenStax; terbit 2023)", accreditation: "universitas terakreditasi" },
  ],
  pm: [
    { title: "PM² Project Management Methodology Guide 3.1 (European Commission)", url: "https://op.europa.eu/en/publication-detail/-/publication/97cc2f12-c648-11ee-95d9-01aa75ed71a1", kind: "guide", description: "Panduan metodologi manajemen proyek resmi Komisi Eropa (PDF gratis, CC BY 4.0, tersedia dalam beberapa bahasa): siklus hidup proyek dari initiating sampai closing, tata kelola dan peran, artefak seperti business case, project charter dan project work plan, serta pemantauan dan pengendalian.", publisher: "European Commission, Directorate-General for Digital Services (Publications Office of the European Union)", year: "2023 (edisi 3.1; dimuat di Publications Office Februari 2024)", accreditation: "badan pemerintah" },
    { title: "ISO 21502:2020 Project, programme and portfolio management, Guidance on project management (halaman resmi ISO)", url: "https://www.iso.org/standard/74947.html", kind: "standard", description: "Ringkasan resmi ISO (gratis, ada 'Read sample') tentang panduan praktik manajemen proyek untuk organisasi apa pun, termasuk pendekatan prediktif, iteratif dan agile; teks standar lengkap berbayar.", publisher: "International Organization for Standardization (ISO)", year: "2020", accreditation: "badan standar" },
  ],
  concept: [
    { title: "OpenStax Entrepreneurship, bab 4: Creativity, Innovation, and Invention", url: "https://openstax.org/books/entrepreneurship/pages/4-introduction", kind: "textbook", description: "Bab buku teks gratis tentang alat untuk kreativitas dan inovasi, perbedaan kreativitas, inovasi dan invensi, serta cara mengembangkan ide menjadi konsep yang bisa diuji. Cocok sebagai dasar merancang konsep event.", publisher: "OpenStax (Rice University)", year: "2026 (revisi web 17 Juni 2026 per metadata buku OpenStax; terbit 2020)", accreditation: "universitas terakreditasi" },
    { title: "NSW Government Event Starter Guide: Before you begin organising public and outdoor events", url: "https://www.nsw.gov.au/departments-and-agencies/premiers-department/community-engagement/event-starter-guide/before-you-begin", kind: "guide", description: "Daftar pertanyaan kunci sebelum konsep event diputuskan: tujuan dan sasaran event, lokasi dan biaya sewanya, target audiens, komunikasi, izin dan lisensi, rencana yang dibutuhkan, sumber daya, total biaya, kompetisi dengan event lain, serta return on investment dan dampak ekonomi. Membantu menguji apakah ide event layak dijalankan.", publisher: "NSW Government, Premier's Department (Australia)", year: "2024 (metadata halaman dateModified 29/01/2024)", accreditation: "badan pemerintah" },
    { title: "Entrepreneurship: from ideas to reality (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/money-business/entrepreneurship-ideas-reality/content-section-overview", kind: "course", description: "Kursus gratis 24 jam (Level 2) tentang menghasilkan dan mengevaluasi ide, menyusun model bisnis, pilihan pendanaan, dan langkah memulai usaha, dengan studi kasus wirausaha nyata. Bagian pembangkitan dan evaluasi ide bisa dipakai untuk menyaring konsep event.", publisher: "The Open University (OpenLearn)", year: "2026 (diperbarui 03/03/2026; terbit 13/09/2018)", accreditation: "universitas terakreditasi" },
  ],
  proposal: [
    { title: "HSE Event safety: Getting started", url: "https://www.hse.gov.uk/event-safety/getting-started.htm", kind: "guide", description: "Panduan resmi HSE Inggris tentang langkah awal merencanakan event: struktur tanggung jawab, rencana keselamatan, memilih kontraktor, koordinasi dengan venue dan layanan darurat, plus checklist perencanaan.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2024 (diperbarui 11/10/2024)", accreditation: "badan pemerintah" },
    { title: "University of Exeter Event Toolkit: Planning an event", url: "https://www.exeter.ac.uk/departments/communication/communications/events/toolkit/planning-event/", kind: "university", description: "Toolkit universitas berisi tahapan perencanaan event dari tujuan, anggaran, timeline sampai checklist, template agenda dan formulir pembicara, serta panduan aksesibilitas.", publisher: "University of Exeter, Marketing, Student Recruitment and Communications", year: "2026 (header HTTP Last-Modified 22 Jul 2026)", accreditation: "universitas terakreditasi" },
    { title: "Thurrock Council: Event Management Plan (EMP) template", url: "https://www.thurrock.gov.uk/sites/default/files/assets/documents/event-management-plan-v01.pdf", kind: "guide", description: "Template EMP 30 halaman dari pemerintah daerah Inggris dengan catatan panduan tiap bagian, untuk event kecil di bawah 500 orang sampai festival di atas 10.000 orang, termasuk tenggat pengajuan ke Safety Advisory Group.", publisher: "Thurrock Council (pemerintah daerah, Inggris)", year: "2022 (metadata PDF April 2022)", accreditation: "badan pemerintah" },
  ],
  bizplan: [
    { title: "U.S. SBA: Plan your business (bagian Write your business plan)", url: "https://www.sba.gov/counseling/plan-your-business/#business-plan", kind: "guide", description: "Panduan pemerintah AS tentang format business plan tradisional dan lean startup, sembilan bagian bakunya, plus contoh unduhan dan kalkulator break-even. URL lama /business-guide/plan-your-business/write-your-business-plan kini dialihkan ke halaman ini.", publisher: "U.S. Small Business Administration (SBA)", year: "2026 (metadata halaman dateModified 08/09/2026; terbit 18/12/2025)", accreditation: "badan pemerintah" },
    { title: "OpenStax Entrepreneurship, bab 11: Business Model and Plan", url: "https://openstax.org/books/entrepreneurship/pages/11-introduction", kind: "textbook", description: "Bab buku teks gratis tentang merancang model bisnis, analisis kelayakan, dan menyusun business plan yang berfokus pada pelanggan.", publisher: "OpenStax (Rice University)", year: "2026 (revisi web 17 Juni 2026 per metadata buku OpenStax; terbit 2020)", accreditation: "universitas terakreditasi" },
    { title: "business.gov.au: Develop your business plan", url: "https://business.gov.au/planning/business-plans/develop-your-business-plan", kind: "guide", description: "Panduan Pemerintah Australia untuk menyusun rencana bisnis, dengan template business plan (DOCX) gratis dan alat perencanaan daring sederhana, termasuk tips menyiapkan bagian keuangan dan ringkasan eksekutif.", publisher: "Pemerintah Australia (business.gov.au)", year: "2024 (metadata halaman dcterms.date 07 November 2024)", accreditation: "badan pemerintah" },
  ],
  bud: [
    { title: "OpenStax Principles of Accounting Vol. 2, 7.1 Describe How and Why Managers Use Budgets", url: "https://openstax.org/books/principles-managerial-accounting/pages/7-1-describe-how-and-why-managers-use-budgets", kind: "textbook", description: "Awal bab budgeting buku teks gratis: fungsi anggaran, pendekatan top-down, bottom-up dan zero-based, anggaran statis dan fleksibel, serta master budget.", publisher: "OpenStax (Rice University)", year: "2024 (revisi web 29 Juli 2024 per metadata buku OpenStax; terbit 2019)", accreditation: "universitas terakreditasi" },
    { title: "Brighton Council (Tasmania): Event Management Kit, bagian Budget dan checklist Budget & Funding", url: "https://www.brighton.tas.gov.au/wp-content/uploads/2025/07/FINAL-Event-Management-Kit-8-July-25.pdf", kind: "guide", description: "Bagian Budget kit pemerintah daerah Australia ini menekankan menyusun anggaran sejak awal, memasukkan semua pos biaya, akurasi estimasi, dan target tetap 'in the black' saat event selesai; checklist Budget & Funding di akhir kit mencakup menyiapkan anggaran, memantau pengeluaran, dan memfinalkan anggaran.", publisher: "Brighton Council (pemerintah daerah, Tasmania, Australia)", year: "2025 (edisi 8 Juli 2025; metadata PDF 15 Jul 2025)", accreditation: "badan pemerintah" },
    { title: "University of Exeter Event Toolkit: Budget and costing events", url: "https://www.exeter.ac.uk/departments/communication/communications/events/toolkit/budget-costing/", kind: "university", description: "Cara menyusun anggaran dan menghitung biaya event, termasuk template anggaran untuk konferensi dan workshop, pengajuan dana, dan pengendalian pengeluaran lewat purchase order.", publisher: "University of Exeter, Marketing, Student Recruitment and Communications", year: "2024 (header HTTP Last-Modified 15 Jul 2024)", accreditation: "universitas terakreditasi" },
  ],
  team: [
    { title: "Working in teams (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/money-business/working-teams", kind: "course", description: "Kursus gratis 24 jam (Level 1, dengan badge digital) delapan minggu tentang dasar kerja tim, tim virtual, tahap perkembangan tim, peran individu, teknik komunikasi, manfaat keberagaman dan aspek budaya, serta cara menunjukkan kompetensi kerja tim kepada pemberi kerja.", publisher: "The Open University (OpenLearn)", year: "2025 (terbit dan diperbarui 25/11/2025)", accreditation: "universitas terakreditasi" },
    { title: "Working in the voluntary sector (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/society-politics-law/sociology/working-the-voluntary-sector/content-section-overview", kind: "course", description: "Kursus gratis 24 jam yang di minggu ke-2 khusus membahas merekrut, melatih, memotivasi, dan mempertahankan relawan.", publisher: "The Open University (OpenLearn)", year: "2020 (diperbarui 09/01/2020)", accreditation: "universitas terakreditasi" },
    { title: "HSE Event safety: roles at events", url: "https://www.hse.gov.uk/event-safety/roles.htm", kind: "guide", description: "Tanggung jawab tiap peran di event: organiser, kontraktor, pemilik venue, supervisor, pekerja, relawan, dan organisasi sukarela. Berguna untuk briefing dan pembagian peran kru.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2023 (diperbarui 16/03/2023)", accreditation: "badan pemerintah" },
  ],
  mkt: [
    { title: "Marketing communications in the digital age (OpenLearn, The Open University)", url: "https://www.open.edu/openlearn/money-business/marketing/marketing-communications-the-digital-age/content-section-0", kind: "course", description: "Kursus gratis 12 jam (Level 2) tentang model komunikasi pemasaran, desain pesan, etika, dan alat digital termasuk media sosial, email, dan online PR.", publisher: "The Open University (OpenLearn)", year: "2026 (diperbarui 03/03/2026; terbit 2022)", accreditation: "universitas terakreditasi" },
    { title: "OpenStax Principles of Marketing", url: "https://openstax.org/books/principles-marketing/pages/1-1-marketing-and-the-marketing-process", kind: "textbook", description: "Buku teks pemasaran gratis yang bisa dibaca per bab, termasuk bab 13 komunikasi pemasaran terpadu, bab 14 iklan dan PR, dan bab 16 direct, online, social media, dan mobile marketing.", publisher: "OpenStax (Rice University)", year: "2026 (revisi web 18 Agustus 2026 per metadata buku OpenStax; terbit 2023)", accreditation: "universitas terakreditasi" },
    { title: "NSW Government Event Starter Guide: Finding sponsors for your event", url: "https://www.nsw.gov.au/departments-and-agencies/premiers-department/community-engagement/event-starter-guide/sponsorship", kind: "guide", description: "Panduan pemerintah negara bagian NSW tentang mencari sponsor event: riset calon sponsor yang selaras dengan nilai event, bertemu langsung, menyusun proposal yang disesuaikan dengan tujuan bisnis sponsor, paket sponsor bertingkat, perjanjian tertulis, dan menjaga hubungan sponsor.", publisher: "NSW Government, Premier's Department (Australia)", year: "2024 (metadata halaman dateModified 29/01/2024)", accreditation: "badan pemerintah" },
  ],
  tech: [
    { title: "HSE Event safety: Outdoor equipment to support speaker clusters, lights etc", url: "https://www.hse.gov.uk/event-safety/outdoor-equipment.htm", kind: "guide", description: "Panduan HSE tentang peralatan penopang speaker cluster, lampu dan perangkat lain di event luar ruang (beban bisa sampai 500 kg dan digantung 6 m atau lebih): kewajiban penyelenggara, pemilihan peralatan yang fit-for-purpose, dan checklist dos and don'ts agar struktur penopang tidak terguling atau roboh.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2024 (diperbarui 12/10/2024)", accreditation: "badan pemerintah" },
    { title: "Technical Theatre Practicum (Boltz), 1.7 Stage Lighting (LibreTexts)", url: "https://human.libretexts.org/Bookshelves/Theater_Film_and_Storytelling/Technical_Theatre_Practicum_(Boltz)/01:_Chapters/1.07:_Stage_Lighting", kind: "textbook", description: "Bab singkat (CC BY 4.0) tentang dasar tata cahaya panggung: membaca light plot, pemasangan dan focusing, serta sesi cueing; bab 1.9 di buku yang sama membahas dasar tata suara.", publisher: "Humanities LibreTexts (proyek OER berbasis University of California, Davis); penulis Christopher R. Boltz", year: "2020 (diperbarui 29/07/2020)", accreditation: "universitas terakreditasi" },
    { title: "HSE Event safety: Temporary demountable structures", url: "https://www.hse.gov.uk/event-safety/temporary-demountable-structures.htm", kind: "guide", description: "Panduan keselamatan pemasangan dan pembongkaran struktur sementara (panggung, tower speaker, lighting) serta pemilihan peralatan penopangnya.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2023 (diperbarui 16/03/2023)", accreditation: "badan pemerintah" },
  ],
  prodplan: [
    { title: "HSE Event safety: Managing an event", url: "https://www.hse.gov.uk/event-safety/managing-an-event.htm", kind: "guide", description: "Mengelola keselamatan selama build-up, load-in, breakdown, dan load-out: koordinasi kontraktor, briefing kru, pemantauan, dan debrief.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2024 (diperbarui 12/10/2024)", accreditation: "badan pemerintah" },
    { title: "HSE Event safety: Transport", url: "https://www.hse.gov.uk/event-safety/transport.htm", kind: "guide", description: "Pengelolaan lalu lintas kendaraan dan pejalan kaki di lokasi event, termasuk pergerakan kendaraan produksi saat load in dan load out serta koordinasi penutupan jalan.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2025 (diperbarui 04/09/2025)", accreditation: "badan pemerintah" },
    { title: "Brighton Council (Tasmania): Event Management Kit, 8 July 2025", url: "https://www.brighton.tas.gov.au/wp-content/uploads/2025/07/FINAL-Event-Management-Kit-8-July-25.pdf", kind: "guide", description: "Kit 35 halaman dari pemerintah daerah Australia untuk penyelenggara event, termasuk bagian Program Schedule/Run Sheet yang menjelaskan isi running sheet (bump in, jadwal acara, bump out) dan checklist dokumen yang wajib disiapkan.", publisher: "Brighton Council (pemerintah daerah, Tasmania, Australia)", year: "2025 (edisi 8 Juli 2025; metadata PDF 15 Jul 2025)", accreditation: "badan pemerintah" },
  ],
  venue: [
    { title: "HSE Event safety: Venue and site design", url: "https://www.hse.gov.uk/event-safety/venue-site-design.htm", kind: "guide", description: "Menilai kapasitas venue, kondisi tanah dan struktur, akses kendaraan dan pejalan kaki, serta menyusun site plan (struktur, fasilitas, pagar, pintu masuk dan keluar).", publisher: "Health and Safety Executive (HSE), Inggris", year: "2024 (diperbarui 12/10/2024)", accreditation: "badan pemerintah" },
    { title: "University of Exeter Event Toolkit: Booking facilities", url: "https://www.exeter.ac.uk/departments/communication/communications/events/toolkit/booking-facilities/", kind: "university", description: "Contoh alur memesan ruang, katering, peralatan audiovisual, parkir dan keamanan untuk event, termasuk rekomendasi venue dan perkiraan tarif delegasi.", publisher: "University of Exeter, Marketing, Student Recruitment and Communications", year: "2026 (header HTTP Last-Modified 27 Jul 2026; syarat sewa ruang luar bertanggal 6 Des 2024)", accreditation: "universitas terakreditasi" },
    { title: "City of Sydney: Venue Hire Agreement (community venues, not staffed)", url: "https://www.cityofsydney.nsw.gov.au/-/media/corporate/files/places-and-spaces/community-centres/conditions-of-hire/booking-confirmation-and-special-conditions-venues-unstaffed.pdf?download=true", kind: "guide", description: "Contoh nyata kontrak sewa venue dari pemerintah kota: syarat pemesanan, deposit, kewajiban penyewa, hak inspeksi, dan kondisi khusus.", publisher: "City of Sydney (pemerintah kota, Australia)", year: "2021 (metadata PDF Maret 2021)", accreditation: "badan pemerintah" },
  ],
  reg: [
    { title: "NSW Government (NSW Fair Trading): Ticket reselling", url: "https://www.nsw.gov.au/legal-and-justice/consumer-rights-and-protection/services/ticket-reselling", kind: "guide", description: "Aturan tiket di NSW yang berguna saat menyusun syarat tiket: larangan menjual kembali tiket untuk mencari untung (hukum anti-scalping NSW sejak 1 Juni 2018), syarat iklan resale, standar informasi resale yang harus dicantumkan penyelenggara pada tiket dan iklan, penanganan event batal dan refund, sanksi, hak konsumen, bukti pembelian, dan cara komplain ke NSW Fair Trading.", publisher: "NSW Government, NSW Fair Trading (Australia)", year: "2024 (metadata halaman dateModified 09/12/2024)", accreditation: "badan pemerintah" },
    { title: "NSW Government: Toolkit for Accessible and Inclusive Events", url: "https://www.nsw.gov.au/sites/default/files/2023-07/Toolkit-for-Accessible-and-Inclusive-Events.pdf", kind: "guide", description: "Checklist, simbol aksesibilitas, panduan bahasa inklusif, dan contoh formulir registrasi aksesibilitas agar pendaftaran dan check-in inklusif.", publisher: "NSW Government, Premier's Department (Australia)", year: "2026 (edisi Juli 2026)", accreditation: "badan pemerintah" },
    { title: "University of Exeter Event Toolkit: Eventbrite, event marketing and publicity", url: "https://www.exeter.ac.uk/departments/communication/communications/events/toolkit/eventbriteeventmarketingandpublicity/", kind: "university", description: "Memakai Eventbrite atau Microsoft Forms untuk registrasi peserta, memilih toko daring untuk tiket berbayar, dan menggabungkannya dengan promosi event; ada panduan Eventbrite yang bisa diunduh.", publisher: "University of Exeter, Marketing, Student Recruitment and Communications", year: "2024 (panduan Eventbrite tertanggal September 2024)", accreditation: "universitas terakreditasi" },
  ],
  risk: [
    { title: "ISO 31000:2018 Risk management, Guidelines (halaman resmi ISO)", url: "https://www.iso.org/standard/65694.html", kind: "standard", description: "Ringkasan resmi ISO (gratis, ada 'Read sample') tentang prinsip, kerangka, dan proses manajemen risiko; teks standar lengkap berbayar. Dikecualikan dari batas tahun 2020 karena masih edisi yang berlaku: halaman ISO menyatakan standar ini terakhir ditinjau dan dikonfirmasi pada 2023 dan belum ada edisi pengganti yang terbit (revisi ISO/CD 31000 masih dalam pengembangan).", publisher: "International Organization for Standardization (ISO)", year: "2018 (edisi berlaku, dikonfirmasi ISO 2023; stage 90.92, revisi masih dalam pengembangan)", accreditation: "badan standar", exempt: "standar yang masih berlaku" },
    { title: "HSE: Managing risks and risk assessment at work", url: "https://www.hse.gov.uk/simple-health-safety/risk/index.htm", kind: "guide", description: "Langkah demi langkah menyusun risk assessment (identifikasi bahaya, nilai risiko, kendali) lengkap dengan template dan contoh.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2025 (diperbarui 24/03/2025)", accreditation: "badan pemerintah" },
    { title: "HSE Event safety: Planning for incidents and emergencies", url: "https://www.hse.gov.uk/event-safety/incidents-and-emergencies.htm", kind: "guide", description: "Menyusun emergency plan event: evakuasi, show stop, koordinasi dengan polisi dan ambulans, uji table-top, dan rencana kontingensi.", publisher: "Health and Safety Executive (HSE), Inggris", year: "2026 (diperbarui 20/01/2026)", accreditation: "badan pemerintah" },
  ],
  bizdoc: [
    { title: "OpenStax Business Law I Essentials, bab 7: Contract Law", url: "https://openstax.org/books/business-law-i-essentials/pages/7-introduction", kind: "textbook", description: "Unsur kontrak yang sah (kesepakatan, consideration, kapasitas, legalitas), pelanggaran dan pemulihannya, dasar untuk memahami kontrak klien dan vendor.", publisher: "OpenStax (Rice University)", year: "2026 (revisi web 21 Mei 2026 per metadata buku OpenStax; terbit 2019)", accreditation: "universitas terakreditasi" },
    { title: "business.gov.au: Prepare a contract", url: "https://business.gov.au/people/contractors/prepare-a-contract", kind: "guide", description: "Panduan Pemerintah Australia tentang 14 unsur yang perlu ada dalam kontrak kerja sama: pihak, lingkup pekerjaan, pembayaran, kekayaan intelektual, kerahasiaan, asuransi, subkontrak, penyelesaian sengketa, variasi, dan pengakhiran, dengan contoh dan saran bahasa sederhana. URL lama /legal/contracts-and-tenders/prepare-a-contract kini dialihkan ke halaman ini.", publisher: "Pemerintah Australia (business.gov.au)", year: "2025 (metadata halaman dcterms.date 01 August 2025)", accreditation: "badan pemerintah" },
    { title: "NSW Government Event Starter Guide: Documentation for your public and outdoor event", url: "https://www.nsw.gov.au/departments-and-agencies/premiers-department/community-engagement/event-starter-guide/documentation", kind: "guide", description: "Dokumen yang perlu disusun dan disimpan penyelenggara event: event plan (isi lengkapnya dari waktu bump in dan bump out, run sheet, production schedule, site plan, struktur komando, daftar izin, sampai rencana keamanan dan darurat), financial plan, budget, communications plan, marketing plan, dokumen formal lain, dan catatan prosedur, plus alasan menyimpan arsip untuk kepatuhan hukum dan evaluasi.", publisher: "NSW Government, Premier's Department (Australia)", year: "2024 (metadata halaman dateModified 30/01/2024)", accreditation: "badan pemerintah" },
  ],
  prod: [
    { title: "CCSU Theatre: Stage Management and Assistant Stage Management Handbook (2023)", url: "https://www.ccsu.edu/sites/default/files/2024-06/SM%20and%20ASM%20Handbook.pdf", kind: "university", description: "Buku pegangan yang merunut kerja stage manager dari pra-produksi, rehearsal, tech rehearsal, calling cues, show run, sampai strike dan laporan pasca-show.", publisher: "Central Connecticut State University, Theatre Department", year: "2023 (PDF dimuat Juni 2024)", accreditation: "universitas terakreditasi" },
    { title: "Technical Theatre Practicum (Boltz), 1.11 Production Reports (LibreTexts)", url: "https://human.libretexts.org/Bookshelves/Theater_Film_and_Storytelling/Technical_Theatre_Practicum_(Boltz)/01:_Chapters/1.11:_Production_Reports", kind: "textbook", description: "Laporan produksi (rehearsal report dan performance report) yang disusun per departemen sebagai bagian dari dokumen produksi.", publisher: "Humanities LibreTexts (proyek OER berbasis University of California, Davis); penulis Christopher R. Boltz", year: "2020 (diperbarui 29/07/2020)", accreditation: "universitas terakreditasi" },
    { title: "Theatre UCF Stage Management Handbook (Last Revised August 2021)", url: "https://cah.ucf.edu/performingarts/wp-content/uploads/sites/46/2020/10/Stage-Management-Handbook-2021.pdf", kind: "university", description: "Buku pegangan 51 halaman program BFA Stage Management University of Central Florida: kalender produksi, jadwal rehearsal dan tech, isi prompt book dan calling script, serta prosedur dan dokumen yang wajib dijaga stage manager.", publisher: "Theatre UCF, University of Central Florida", year: "2021 (Last Revised August 2021)", accreditation: "universitas terakreditasi" },
  ],
  show: [
    { title: "Technical Theatre Practicum (Boltz), 1.12 Cueing Scripts (LibreTexts)", url: "https://human.libretexts.org/Bookshelves/Theater_Film_and_Storytelling/Technical_Theatre_Practicum_(Boltz)/01:_Chapters/1.12:_Cueing_Scripts", kind: "textbook", description: "Cara memanggil cue: warning, standby, go, penomoran cue lampu (LQ) dan suara (SQ), dan menandai naskah untuk cueing.", publisher: "Humanities LibreTexts (proyek OER berbasis University of California, Davis); penulis Christopher R. Boltz", year: "2020 (diperbarui 23/05/2020)", accreditation: "universitas terakreditasi" },
    { title: "CCSU Theatre: Stage Management Handbook (bagian Calling Cues dan Show Run)", url: "https://www.ccsu.edu/sites/default/files/2024-06/SM%20and%20ASM%20Handbook.pdf", kind: "university", description: "Bagian Calling Cues, Pre-Performance/Run Routine, dan Show Run menjelaskan prosedur show calling dan penanganan insiden saat pertunjukan.", publisher: "Central Connecticut State University, Theatre Department", year: "2023 (PDF dimuat Juni 2024)", accreditation: "universitas terakreditasi" },
  ],
  crowd: [
    { title: "HSE Event safety: Crowd management", url: "https://www.hse.gov.uk/event-safety/crowd-management.htm", kind: "guide", description: "Struktur organisasi, penilaian risiko kerumunan, kendali fisik dan prosedural, pemantauan aktif, dan keselamatan area panggung (stage barrier).", publisher: "Health and Safety Executive (HSE), Inggris", year: "2023 (diperbarui 16/03/2023)", accreditation: "badan pemerintah" },
    { title: "Home Office: Terrorism (Protection of Premises) Act 2025 (Martyn's Law), statutory guidance", url: "https://www.gov.uk/government/publications/the-terrorism-protection-of-premises-act-2025", kind: "guide", description: "Panduan statutori Kementerian Dalam Negeri Inggris untuk penanggung jawab tempat dan event berkapasitas 200 orang ke atas (standard duty) dan 800 ke atas (enhanced duty): menilai cakupan, prosedur perlindungan publik saat serangan, dan dokumen pendukung tentang cara memperkirakan jumlah orang yang hadir.", publisher: "Home Office (Pemerintah Inggris)", year: "2026 (terbit 15 April 2026; diperbarui 25 Agustus 2026)", accreditation: "badan pemerintah" },
    { title: "ANZCTC: Australia's Strategy for Protecting Crowded Places from Terrorism (2023)", url: "https://www.nationalsecurity.gov.au/crowded-places-subsite/Files/australias-strategy-protecting-crowded-places-terrorism.pdf", kind: "guide", description: "Strategi resmi Pemerintah Australia (PDF 24 halaman) untuk pemilik dan penyelenggara tempat ramai termasuk event: prinsip kemitraan dengan polisi, penilaian risiko, langkah mitigasi proporsional, dan rujukan ke alat self-assessment dan security audit crowded places.", publisher: "Australia-New Zealand Counter-Terrorism Committee (Commonwealth of Australia)", year: "2023", accreditation: "badan pemerintah" },
  ],
  eval: [
    { title: "NSW Government Event Starter Guide: Evaluating your event", url: "https://www.nsw.gov.au/departments-and-agencies/premiers-department/community-engagement/event-starter-guide/evaluating-your-event", kind: "guide", description: "Cara mengevaluasi event terhadap tujuan dan anggaran: survei peserta selama atau sesudah event (termasuk pertanyaan demografi dan ingatan terhadap sponsor), rapat debrief dengan staf, relawan, otoritas dan layanan darurat, serta memakai hasilnya untuk laporan ke manajemen, komite dan sponsor dan untuk perencanaan event berikutnya.", publisher: "NSW Government, Premier's Department (Australia)", year: "2024 (metadata halaman dateModified 29/01/2024)", accreditation: "badan pemerintah" },
    { title: "ISO 20121:2024 Event sustainability management systems (halaman resmi ISO)", url: "https://www.iso.org/standard/86389.html", kind: "standard", description: "Ringkasan resmi ISO edisi 2024 tentang sistem manajemen keberlanjutan event; teks standar berbayar.", publisher: "International Organization for Standardization (ISO)", year: "2024", accreditation: "badan standar" },
    { title: "Events Industry Council: Sustainable Event Standards", url: "https://insights.eventscouncil.org/Sustainability/Sustainability-Events-Standards", kind: "standard", description: "Ringkasan delapan standar EIC dengan kriteria dan level Foundations, Bronze, Silver, Gold, Platinum yang bisa dijadikan KPI laporan pasca-event; halaman juga memuat daftar organisasi tersertifikasi dan dokumen SES Targeted Refinement Project.", publisher: "Events Industry Council (EIC)", year: "2026 (daftar organisasi tersertifikasi bertanda 'as of August 2026'; metadata PDF SES Targeted Refinement Project 18 Agu 2026)", accreditation: "asosiasi industri" },
  ],
  legal: [
    { title: "GOV.UK: Your guide to organising a street party", url: "https://www.gov.uk/government/publications/your-guide-to-organising-a-street-party/your-guide-to-organising-a-street-party", kind: "guide", description: "Panduan ringkas Pemerintah Inggris tentang izin dan lisensi untuk event komunitas: kapan Temporary Events Notice dibutuhkan (penjualan alkohol, musik), pengajuan penutupan jalan ke council sekitar enam minggu sebelumnya, asuransi public liability, dan keamanan pangan untuk event sekali jalan.", publisher: "Ministry of Housing, Communities and Local Government (sebelumnya Department for Levelling Up, Housing and Communities), Pemerintah Inggris", year: "2025 (diperbarui 21 Januari 2025; terbit 4 Oktober 2021)", accreditation: "badan pemerintah" },
    { title: "NSW Government Event Starter Guide: Music and performers at your event", url: "https://www.nsw.gov.au/departments-and-agencies/premiers-department/community-engagement/event-starter-guide/music-and-performers", kind: "guide", description: "Panduan pemerintah negara bagian NSW tentang hak cipta musik di event: lisensi gabungan OneMusic Australia (APRA AMCOS dan PPCA) untuk musik live, musik rekaman, dan video bermusik, pengajuan lisensi minimal tiga minggu sebelum event, serta asuransi, K3, dan kontrak dengan pengisi acara.", publisher: "NSW Government, Premier's Department (Australia)", year: "2024 (metadata halaman dateModified 27/08/2024)", accreditation: "badan pemerintah" },
    { title: "SELMI (LMK di bawah LMKN): Public Performance License", url: "https://selmi.or.id/en/music-licensing/public-performance-license/", kind: "guide", description: "Penjelasan lembaga manajemen kolektif Indonesia (didelegasikan LMKN, dibentuk berdasarkan UU Hak Cipta) tentang lisensi pertunjukan publik musik untuk konser, konferensi, pameran, dan bazar.", publisher: "SELMI (Sentra Lisensi Musik Indonesia), LMK di bawah LMKN", year: "2024 (halaman terbit 16 April 2024)", accreditation: "asosiasi industri" },
  ],
};
