import { unit } from "./units.mjs";
import { uni } from "./universities.mjs";

// Fase 2 (Uang) dan Fase 3 (Produksi)
export const TOPICS_B = [
  {
    slug: "bud",
    title: "Budgeting: anggaran dan kontrol biaya event",
    curriculum_ref: "Knowledge 4",
    phase_id: 2, week_from: 5, week_to: 6, sort_order: 5,
    summary: "Anggaran adalah rencana event dalam angka. Dua minggu ini melatih menyusun anggaran dari nol, menetapkan margin dan cadangan, memantau realisasi, dan menjaga arus kas agar EO tidak menalangi klien.",
    units: [unit("SITXFIN009"), unit("SITXFIN010")],
    university: [uni("psu", "HM 336 Hospitality Managerial Accounting"), uni("ehl", "9302IC Managerial Accounting")],
    points: [
      "Anggaran disusun per kategori biaya: venue, produksi teknis, dekorasi, catering, dokumentasi, hiburan, kru, transportasi, perizinan, dan lain-lain, ditambah cadangan 5 sampai 10 persen.",
      "Bedakan biaya tetap (sewa venue) dan biaya variabel (catering per pax). Biaya variabel ikut berubah saat jumlah tamu berubah.",
      "Margin dihitung dari total biaya, bukan dari harga jual. Harga jual = biaya + cadangan + margin yang kamu inginkan.",
      "Arus kas direncanakan per termin: DP klien harus menutup DP vendor, pelunasan klien sebelum pelunasan vendor.",
      "Selama produksi, catat realisasi tiap pengeluaran di kolom sebelah anggaran. Selisih di atas 10 persen pada satu kategori harus dilaporkan dan diputuskan, bukan didiamkan.",
      "Laporan keuangan event sederhana setelah acara: anggaran vs realisasi, margin nyata, dan pelajaran untuk penawaran berikutnya.",
    ],
    evidence_brief: "Unggah spreadsheet anggaran vs realisasi dari satu event yang sudah selesai: kategori biaya, anggaran, realisasi, selisih, dan margin akhir. Tulis tiga baris pelajaran keuangan dari event itu.",
    sources: [],
    questions: [
      { stem: "Total biaya event Rp 100 juta dan kamu ingin margin 20 persen dari biaya. Harga jual sebelum cadangan?",
        options: ["Rp 110 juta", "Rp 120 juta", "Rp 125 juta", "Rp 80 juta"],
        correct_index: 1, explanation: "Margin dari biaya: 100 juta + 20 persen x 100 juta = 120 juta. Cadangan ditambahkan terpisah." },
      { stem: "Jumlah tamu naik dari 300 ke 400 orang. Kategori biaya mana yang paling langsung terpengaruh?",
        options: ["Sewa venue (harga paket)", "Catering per pax", "Honor MC", "Biaya desain undangan"],
        correct_index: 1, explanation: "Catering adalah biaya variabel per orang; sewa venue dan honor MC umumnya biaya tetap." },
      { stem: "Realisasi dekorasi melebihi anggaran 18 persen di tengah produksi. Tindakan yang tepat?",
        options: ["Diamkan, tutup dari margin", "Laporkan selisihnya dan putuskan: kurangi lingkup, pakai cadangan, atau ajukan tambahan ke klien", "Batalkan vendor dekorasi", "Kurangi honor kru"],
        correct_index: 1, explanation: "Selisih besar harus diputuskan secara sadar. Mendiamkannya menghabiskan margin tanpa keputusan." },
    ],
  },
  {
    slug: "bizplan",
    title: "Business plan untuk usaha EO dan WO",
    curriculum_ref: "Knowledge 3",
    phase_id: 2, week_from: 7, week_to: 7, sort_order: 6,
    summary: "Rencana bisnis menjawab: siapa pelanggan, layanan apa yang dijual, berapa harga dan biayanya, dan bagaimana usaha tumbuh. Topik ini menyusun rencana bisnis ringkas satu tahun untuk usaha eventmu.",
    units: [unit("BSBESB401"), unit("BSBOPS502")],
    university: [uni("ulster", "The Business Plan"), uni("surrey", "Business Plan and Start-Up Ventures")],
    points: [
      "Rencana bisnis satu halaman cukup untuk mulai: segmen pelanggan, layanan, keunggulan, saluran pemasaran, struktur biaya, sumber pendapatan, dan target angka.",
      "Segmen yang jelas mengalahkan pasar yang luas: 'wedding intimate 100 sampai 300 tamu di kota X' lebih mudah dipasarkan daripada 'semua acara'.",
      "Hitung titik impas bulanan: biaya tetap usaha (gaji inti, kantor, alat) dibagi margin rata-rata per event menghasilkan jumlah event minimum per bulan.",
      "Proyeksi 12 bulan memuat musim ramai dan sepi. Rencanakan kas untuk bulan sepi dari surplus bulan ramai.",
      "Rencana operasional menurunkan target tahunan menjadi kegiatan bulanan: berapa prospek dihubungi, berapa proposal dikirim, berapa event dijalankan.",
      "Tinjau rencana tiap kuartal: bandingkan target dan realisasi, lalu ubah satu hal saja untuk kuartal berikutnya.",
    ],
    evidence_brief: "Tulis rencana bisnis satu halaman untuk usaha eventmu untuk 12 bulan ke depan, termasuk perhitungan titik impas bulanan dan target jumlah event per bulan. Lampirkan proyeksi kas sederhana per bulan.",
    sources: [],
    questions: [
      { stem: "Biaya tetap usaha Rp 30 juta per bulan dan margin rata-rata per event Rp 10 juta. Berapa event minimum per bulan untuk impas?",
        options: ["1", "2", "3", "4"],
        correct_index: 2, explanation: "Titik impas = biaya tetap dibagi margin per event = 30 juta / 10 juta = 3 event." },
      { stem: "Mengapa segmen pelanggan yang sempit sering lebih menguntungkan bagi EO kecil?",
        options: ["Karena pesaing lebih sedikit di semua segmen", "Pesan pemasaran, portofolio, dan proses jadi lebih tajam dan mudah dipercaya", "Karena harga bisa lebih rendah", "Tidak ada alasan, pasar luas selalu lebih baik"],
        correct_index: 1, explanation: "Segmen sempit memungkinkan spesialisasi yang terlihat oleh calon klien dan efisiensi proses." },
      { stem: "Apa fungsi tinjauan kuartalan rencana bisnis?",
        options: ["Menulis ulang seluruh rencana", "Membandingkan target dan realisasi lalu mengubah satu hal untuk kuartal berikutnya", "Mengganti segmen pelanggan", "Menaikkan harga"],
        correct_index: 1, explanation: "Tinjauan rutin menjaga rencana tetap dipakai. Mengubah satu hal saja membuat dampaknya bisa diukur." },
    ],
  },
  {
    slug: "bizdev",
    title: "Business development: prospek, penjualan, dan hubungan bisnis",
    curriculum_ref: "Official: Business Development",
    phase_id: 2, week_from: 8, week_to: 8, sort_order: 7,
    summary: "Event datang dari hubungan. Topik ini membahas cara mencari prospek, mengelola pipeline penjualan, bernegosiasi, dan menjaga hubungan dengan klien, venue, dan vendor supaya pekerjaan berulang.",
    units: [unit("SITXMPR011"), unit("SITXMGT005")],
    university: [uni("ucf", "HFT3523 Event Sales"), uni("lesroches_msc", "Event Design & Management")],
    points: [
      "Pipeline penjualan punya tahap tetap: prospek, kontak pertama, brief, proposal, negosiasi, kontrak. Catat tiap prospek di tahap mana dan kapan tindak lanjut berikutnya.",
      "Sumber prospek terbaik EO dan WO: klien lama, rujukan vendor dan venue, serta komunitas. Media sosial memperkuat, bukan menggantikan.",
      "Negosiasi dimulai dari mengetahui batas bawahmu (harga minimum yang masih untung) dan hal yang bisa ditukar selain harga: lingkup, termin, tanggal.",
      "Hubungan dengan venue dan vendor dibangun dengan bayar tepat waktu, brief yang jelas, dan ucapan terima kasih tertulis setelah event.",
      "Tindak lanjut setelah event: kirim foto terpilih, minta testimoni, dan tanyakan rencana acara berikutnya dalam 30 hari.",
      "Laporan penjualan bulanan sederhana: jumlah prospek baru, proposal terkirim, tingkat konversi, nilai kontrak.",
    ],
    evidence_brief: "Buat pipeline penjualan (spreadsheet) berisi minimal 10 prospek nyata dengan tahap dan tanggal tindak lanjut, plus satu laporan penjualan bulan lalu. Tambahkan catatan satu negosiasi nyata: batas bawahmu, apa yang ditukar, hasilnya.",
    sources: [],
    questions: [
      { stem: "Calon klien meminta diskon 15 persen dari harga penawaran. Persiapan apa yang paling menentukan sebelum kamu menjawab?",
        options: ["Mengetahui harga pesaing", "Mengetahui batas bawah harga dan hal lain yang bisa ditukar (lingkup, termin, tanggal)", "Menyiapkan alasan menolak", "Menghubungi vendor untuk minta potongan"],
        correct_index: 1, explanation: "Negosiasi yang sehat bertumpu pada batas bawah yang jelas dan alternatif tukar selain harga." },
      { stem: "Mana sumber prospek yang biasanya paling tinggi tingkat konversinya untuk WO?",
        options: ["Iklan berbayar ke audiens umum", "Rujukan dari klien lama, venue, dan vendor", "Pesan massal ke nomor acak", "Pameran di luar kota"],
        correct_index: 1, explanation: "Rujukan membawa kepercayaan yang sudah terbentuk sehingga siklus penjualan lebih pendek." },
      { stem: "Fungsi utama mencatat tahap tiap prospek di pipeline?",
        options: ["Untuk laporan pajak", "Agar tindak lanjut tidak terlewat dan konversi bisa diukur", "Supaya terlihat profesional", "Agar bisa menaikkan harga"],
        correct_index: 1, explanation: "Pipeline yang tercatat membuat tindak lanjut terjadwal dan memperlihatkan di tahap mana prospek sering hilang." },
    ],
  },
  {
    slug: "prodplan",
    title: "Production planning: jadwal produksi dan logistik",
    curriculum_ref: "Knowledge 8",
    phase_id: 3, week_from: 9, week_to: 9, sort_order: 8,
    summary: "Rencana produksi menerjemahkan konsep menjadi jadwal loading, daftar peralatan, dan alur logistik. Topik ini membangun production schedule dan checklist yang dipakai semua vendor.",
    units: [unit("SITEEVT026"), unit("SITEEVT027")],
    university: [uni("ucf", "HFT4394 Event Operations"), uni("surrey", "Event Operation")],
    points: [
      "Production schedule menyusun urutan pemasangan dari yang paling bawah dan paling lama: rigging dan panggung, listrik, sound dan lighting, dekorasi, meja kursi, lalu detail.",
      "Setiap vendor menerima jam masuk, jam selesai, area kerja, dan kontak koordinator lapangan. Dua vendor di area yang sama pada jam yang sama adalah sumber konflik.",
      "Daftar kebutuhan infrastruktur: daya listrik (kVA), genset cadangan, air, toilet, tenda, akses bongkar muat, parkir kru, area penyimpanan.",
      "Rencana logistik memuat kendaraan, jalur masuk, jadwal pengiriman, dan orang yang menerima barang di lokasi.",
      "Checklist pra-event dicek H-1 dengan berjalan mengikuti alur tamu: dari parkir, pintu masuk, registrasi, area utama, sampai keluar.",
      "Bongkar (load-out) direncanakan sama teliti dengan pemasangan: urutan terbalik, batas waktu venue, dan pemeriksaan kerusakan.",
    ],
    evidence_brief: "Unggah production schedule satu event nyata (per vendor: jam masuk, area, kontak) beserta daftar kebutuhan infrastruktur dan rencana logistiknya. Sertakan foto checklist H-1 yang sudah dicentang.",
    sources: [],
    questions: [
      { stem: "Urutan pemasangan yang paling masuk akal di venue ballroom?",
        options: ["Dekorasi, lalu panggung, lalu sound", "Panggung dan rigging, listrik, sound dan lighting, dekorasi, meja kursi", "Meja kursi dulu supaya ruangan terlihat penuh", "Semua vendor masuk bersamaan agar cepat"],
        correct_index: 1, explanation: "Yang paling bawah dan paling lama dipasang dulu; dekorasi dan furnitur menyusul agar tidak terhalang atau rusak." },
      { stem: "Apa risiko utama saat dua vendor dijadwalkan di area yang sama pada jam yang sama?",
        options: ["Biaya lebih tinggi", "Konflik area kerja yang memperlambat keduanya dan berpotensi merusak hasil", "Tidak ada risiko", "Vendor menjadi lebih cepat"],
        correct_index: 1, explanation: "Production schedule mengatur area dan waktu justru untuk mencegah tabrakan pekerjaan." },
      { stem: "Mengapa checklist H-1 dicek dengan berjalan mengikuti alur tamu?",
        options: ["Supaya olahraga", "Karena kekurangan paling mudah terlihat dari sudut pandang orang yang mengalaminya", "Karena klien memintanya", "Untuk menghitung jumlah kursi"],
        correct_index: 1, explanation: "Berjalan sebagai tamu memperlihatkan penanda arah, pencahayaan, dan antrean yang tidak terlihat dari meja koordinator." },
    ],
  },
  {
    slug: "venue",
    title: "Venue management: pemilihan, site plan, dan kontrak venue",
    curriculum_ref: "Knowledge 9",
    phase_id: 3, week_from: 10, week_to: 10, sort_order: 9,
    summary: "Venue menentukan separuh kualitas event dan sebagian besar biayanya. Topik ini membahas cara menilai venue, menyusun site plan dan layout, serta hal yang harus ada dalam kontrak venue.",
    units: [unit("SITEEVT025")],
    university: [uni("surrey", "Venue Management"), uni("napier_ba", "Facilities Planning for Hospitality, Tourism and Events")],
    points: [
      "Spesifikasi venue disusun dari rencana event: kapasitas (duduk vs berdiri), tinggi plafon untuk rigging, daya listrik, akses loading, parkir, waktu akses, dan aturan vendor luar.",
      "Survei venue memakai checklist tetap dan diambil fotonya: titik listrik, pintu darurat, jalur kabel, area vendor, toilet, dan area tunggu pengantin atau pembicara.",
      "Site plan atau floor plan berskala menunjukkan panggung, meja, jalur evakuasi, posisi FOH (sound), dan alur tamu. Kirim ke semua vendor sebelum loading.",
      "Kontrak venue memuat: jam akses dan bongkar, biaya lembur, deposit kerusakan, vendor wajib (catering, sound), kebijakan pembatalan, dan siapa PIC venue di hari H.",
      "Venue outdoor menambah kebutuhan: tenda, lantai, genset, toilet portabel, dan rencana cuaca (wet weather plan).",
      "Bandingkan minimal dua venue dengan tabel yang sama supaya keputusan berdasar spesifikasi, bukan kesan.",
    ],
    evidence_brief: "Unggah hasil survei satu venue nyata (checklist terisi dan foto), floor plan berskala yang kamu buat untuk event di venue itu, dan tabel perbandingan dua venue dengan kriteria yang sama.",
    sources: [],
    questions: [
      { stem: "Klien ingin panggung dengan rigging truss untuk lighting. Spesifikasi venue mana yang wajib dicek lebih dulu?",
        options: ["Warna dinding", "Tinggi plafon dan titik gantung", "Jumlah toilet", "Harga parkir"],
        correct_index: 1, explanation: "Rigging bergantung pada tinggi plafon dan kekuatan titik gantung. Tanpa itu, konsep lighting harus diubah." },
      { stem: "Apa akibat paling umum jika jam akses venue tidak tertulis di kontrak?",
        options: ["Venue lebih murah", "Biaya lembur atau waktu pemasangan yang terlalu pendek di hari H", "Tidak ada akibat", "Vendor lebih senang"],
        correct_index: 1, explanation: "Jam akses menentukan berapa lama vendor bisa memasang. Ketidakjelasan berujung lembur atau pemasangan terburu-buru." },
      { stem: "Mengapa floor plan harus dikirim ke semua vendor sebelum loading?",
        options: ["Untuk memenuhi syarat venue", "Agar setiap vendor tahu posisi dan area kerja sehingga tidak saling menghalangi", "Supaya klien terkesan", "Karena vendor memintanya"],
        correct_index: 1, explanation: "Floor plan adalah acuan bersama; vendor yang bekerja dari gambar yang sama jarang bertabrakan." },
    ],
  },
  {
    slug: "tech",
    title: "Technical production: sound, lighting, AV, dan panggung",
    curriculum_ref: "Knowledge 7",
    phase_id: 3, week_from: 11, week_to: 11, sort_order: 10,
    summary: "Kamu tidak harus menjadi teknisi, tapi harus bisa membaca kebutuhan teknis, menulis brief untuk vendor, dan mengecek hasilnya. Topik ini memberi dasar sound, lighting, AV, listrik, dan panggung.",
    units: [unit("SITEEVT026")],
    university: [uni("ucf", "HFT3443 Event Technology"), uni("napier_ba", "Festival & Event Design and Delivery")],
    points: [
      "Brief teknis ke vendor berisi: jenis acara, jumlah tamu dan ukuran ruang, kebutuhan input (mic wireless, laptop, instrumen), output (speaker, layar), dan rundown dengan cue.",
      "Sound: kebutuhan mic (handheld, clip-on, headset), monitor untuk pengisi acara, posisi FOH yang bisa mendengar ruangan, dan sound check dengan orang yang benar-benar tampil.",
      "Lighting: bedakan cahaya kerja (agar orang melihat), cahaya suasana (warna, wash), dan cahaya sorot (follow spot, key light untuk dokumentasi).",
      "AV dan LED: resolusi konten harus sesuai rasio layar; minta template ke vendor sebelum desainer membuat konten. Siapkan laptop cadangan dengan file yang sama.",
      "Listrik: hitung kebutuhan total (kVA) dari daftar alat, pisahkan jalur sound dari lighting, siapkan genset cadangan dengan ATS untuk acara penting.",
      "Keselamatan teknis: kabel dilindungi ramp atau lakban di jalur tamu, truss dipasang teknisi bersertifikat, dan sertifikat alat berat disimpan bersama dokumen event.",
    ],
    evidence_brief: "Tulis brief teknis lengkap untuk satu event nyata (input, output, rundown dengan cue, kebutuhan daya) dan unggah bersama gambar penempatan sound, lighting, dan layar di floor plan. Tambahkan catatan hasil sound check.",
    sources: [],
    questions: [
      { stem: "Mengapa sound check sebaiknya dilakukan dengan orang yang benar-benar akan tampil?",
        options: ["Supaya lebih cepat", "Karena volume dan karakter suara tiap orang berbeda, pengaturan yang tepat hanya didapat dari orang itu", "Agar vendor bisa pulang lebih awal", "Tidak ada alasan khusus"],
        correct_index: 1, explanation: "Pengaturan mic dan monitor bergantung pada suara dan kebiasaan orang yang tampil." },
      { stem: "Konten video terlihat gepeng di layar LED. Penyebab yang paling mungkin?",
        options: ["Kabel terlalu panjang", "Rasio konten tidak sama dengan rasio layar", "Lampu terlalu terang", "Laptop terlalu lama"],
        correct_index: 1, explanation: "Konten harus dibuat sesuai rasio dan resolusi layar; karena itu template dari vendor diminta sebelum desain." },
      { stem: "Untuk acara penting, apa fungsi ATS pada genset cadangan?",
        options: ["Mengurangi suara genset", "Memindahkan beban ke genset secara otomatis saat listrik utama padam", "Menghemat bahan bakar", "Menambah daya listrik"],
        correct_index: 1, explanation: "ATS (automatic transfer switch) memindahkan sumber daya tanpa menunggu operator sehingga acara tidak gelap lama." },
    ],
  },
  {
    slug: "prod",
    title: "Event production: dari rencana menjadi acara",
    curriculum_ref: "Knowledge 13",
    phase_id: 3, week_from: 12, week_to: 12, sort_order: 11,
    summary: "Produksi mengoordinasikan semua komponen (teknis, dekorasi, catering, hiburan, dokumentasi) menjadi satu acara yang utuh. Topik ini membahas production book, koordinasi vendor, dan pengelolaan hari H dari sisi produksi.",
    units: [unit("SITEEVT026"), unit("SITEEVT028")],
    university: [uni("napier_ba", "Festival & Event Design and Delivery"), uni("napier_msc", "Festival and Event Management")],
    points: [
      "Production book adalah satu dokumen yang berisi semuanya: kontak, rundown, floor plan, production schedule, brief tiap vendor, rencana risiko, dan checklist. Semua koordinator memegang versi yang sama.",
      "Rapat produksi terakhir (H-3 sampai H-1) mengumpulkan semua vendor untuk membaca rundown bersama dan menyelesaikan tabrakan jadwal.",
      "Struktur komando hari H: satu show director, koordinator per area (panggung, tamu, vendor, klien), dan jalur radio dengan protokol singkat.",
      "Komponen produksi dicek dengan standar yang tertulis di brief: bukan 'bagus atau tidak', tapi 'sesuai brief atau tidak'.",
      "Perubahan di hari H dicatat di log produksi (jam, apa, siapa yang memutuskan) untuk laporan dan evaluasi.",
      "Setelah acara: pengecekan kerusakan bersama venue, pengembalian alat, dan pembayaran vendor sesuai berita acara.",
    ],
    evidence_brief: "Unggah production book satu event nyata (boleh PDF gabungan): kontak, rundown, floor plan, production schedule, brief vendor, checklist. Tambahkan log produksi hari H yang kamu isi.",
    sources: [],
    questions: [
      { stem: "Apa manfaat utama rapat produksi H-3 yang mengumpulkan semua vendor?",
        options: ["Membagikan snack", "Membaca rundown bersama dan menyelesaikan tabrakan jadwal sebelum hari H", "Menegosiasikan harga ulang", "Memilih seragam"],
        correct_index: 1, explanation: "Tabrakan jadwal dan asumsi antar vendor paling murah diselesaikan sebelum loading, bukan di lokasi." },
      { stem: "Cara yang benar menilai apakah dekorasi yang terpasang bisa diterima?",
        options: ["Berdasarkan selera koordinator", "Dibandingkan dengan brief dan gambar yang disetujui klien", "Bertanya ke tamu pertama", "Berdasarkan harga vendor"],
        correct_index: 1, explanation: "Standar penerimaan adalah brief tertulis. Itu yang melindungi EO dan vendor dari perdebatan selera." },
      { stem: "Mengapa perubahan di hari H perlu dicatat di log produksi?",
        options: ["Untuk menyalahkan orang", "Sebagai dasar laporan, tagihan tambahan, dan evaluasi", "Karena aturan venue", "Supaya log terlihat penuh"],
        correct_index: 1, explanation: "Log yang rapi menjadi bukti keputusan dan sumber pelajaran untuk event berikutnya." },
    ],
  },
  {
    slug: "show",
    title: "Show management: rundown, cue, dan show calling",
    curriculum_ref: "Knowledge 14",
    phase_id: 3, week_from: 13, week_to: 13, sort_order: 12,
    summary: "Show management memastikan acara berjalan sesuai rundown menit demi menit. Topik ini membahas cara menulis rundown dan cue sheet, memimpin show sebagai show director, dan menangani penyimpangan tanpa panik.",
    units: [unit("SITEEVT028")],
    university: [uni("surrey", "The UG Live Event Project (Event Delivery & Evaluation)"), uni("ucf", "HFT4795 Entertainment Arts and Events")],
    points: [
      "Rundown menit per menit memuat: jam, durasi, segmen, siapa di panggung, cue sound, cue lighting, cue video, dan catatan. Satu baris satu kejadian.",
      "Cue diberi nomor dan dipanggil dengan pola tetap: 'standby cue 12', jeda, 'go cue 12'. Semua operator menjawab 'standby' saat siap.",
      "Show director berada di posisi yang bisa melihat panggung dan mendengar ruangan, memegang rundown induk, dan menjadi satu-satunya yang memberi 'go'.",
      "Jam acara dipatok pada satu jam acuan (jam show director). Semua radio dan operator menyamakan waktu sebelum pintu dibuka.",
      "Rencana B ada untuk segmen berisiko: pengisi acara terlambat, video tidak jalan, pengantin belum siap. Tiap rencana B punya pemicu dan orang yang memutuskan.",
      "Setelah show: catat selisih jam rencana dan jam nyata tiap segmen untuk evaluasi rundown berikutnya.",
    ],
    evidence_brief: "Unggah rundown menit per menit dan cue sheet dari satu event yang kamu jalankan sebagai show director, ditambah catatan jam nyata tiap segmen dan satu rencana B yang benar-benar dipakai (atau disiapkan).",
    sources: [],
    questions: [
      { stem: "Pola panggilan cue yang benar?",
        options: ["'Cue 12 sekarang' tanpa peringatan", "'Standby cue 12', tunggu jawaban operator, lalu 'go cue 12'", "Menyebut nama operator saja", "Memberi kode warna"],
        correct_index: 1, explanation: "Standby memberi waktu operator bersiap; 'go' yang terpisah memastikan eksekusi serentak." },
      { stem: "Mengapa hanya show director yang boleh memberi perintah 'go'?",
        options: ["Karena jabatannya paling tinggi", "Agar tidak ada dua perintah yang bertentangan dan urutan cue tetap satu", "Supaya operator tidak bosan", "Karena klien memintanya"],
        correct_index: 1, explanation: "Satu sumber perintah mencegah kebingungan operator saat banyak hal terjadi bersamaan." },
      { stem: "Video sambutan tidak jalan saat cue dipanggil. Apa yang menentukan respons tim?",
        options: ["Kepanikan tim", "Rencana B yang sudah disiapkan dengan pemicu dan pengambil keputusan", "Keputusan klien saat itu", "Sound engineer"],
        correct_index: 1, explanation: "Rencana B yang tertulis membuat respons cepat dan terkoordinasi, misalnya MC mengisi sementara operator membuka cadangan." },
    ],
  },
];
