import { unit } from "./units.mjs";
import { uni } from "./universities.mjs";

// Fase 0 (sepanjang program) dan Fase 1 (Fondasi)
export const TOPICS_A = [
  {
    slug: "pb-lead",
    title: "Leadership untuk tim event",
    curriculum_ref: "Personal Behavior 1",
    phase_id: 0, week_from: null, week_to: null, sort_order: 101,
    summary: "Memimpin kru, vendor, dan klien pada hari H menuntut keputusan cepat dan komunikasi yang jelas. Topik ini melatih cara memberi arahan, mendelegasikan, dan menangani konflik tanpa merusak hubungan kerja.",
    units: [unit("SITXHRM009"), unit("SITXCOM010")],
    university: [uni("ehl", "9511AC Leadership & Organizational Behavior"), uni("napier_ba", "Leadership, Innovation and Technology for Tourism, Hospitality and Events")],
    points: [
      "Pemimpin event menetapkan standar lewat contoh: datang paling awal saat loading, memakai radio dengan disiplin, dan menjaga nada bicara saat tekanan tinggi.",
      "Delegasi yang efektif memberi tiga hal: tugas yang jelas, batas wewenang (apa yang boleh diputuskan sendiri), dan waktu lapor balik.",
      "Briefing kru sebelum event memakai struktur tetap: tujuan event, rundown ringkas, peran tiap orang, jalur eskalasi, dan prosedur darurat.",
      "Konflik di lapangan diselesaikan dengan memisahkan orang dari masalah: dengarkan versi kedua pihak, sepakati fakta, baru cari jalan keluar yang bisa dijalankan sekarang.",
      "Umpan balik diberikan segera dan spesifik, dimulai dari perilaku yang terlihat, dampaknya, dan perubahan yang diminta.",
      "Pemimpin yang baik menyiapkan pengganti: setiap posisi kunci punya orang kedua yang tahu rundown dan kontak vendor.",
    ],
    evidence_brief: "Tulis satu halaman refleksi kepemimpinan dari event nyata yang kamu pimpin: satu keputusan sulit yang kamu ambil di hari H, cara kamu mengomunikasikannya ke tim, dan apa yang akan kamu ubah. Lampirkan naskah briefing kru yang kamu pakai.",
    sources: [],
    questions: [
      { stem: "Saat mendelegasikan tugas dekorasi ke koordinator, hal apa yang paling penting kamu sampaikan selain tugasnya?",
        options: ["Nama semua vendor yang pernah kamu pakai", "Batas wewenang dan kapan ia harus lapor balik", "Alasan kamu tidak mengerjakannya sendiri", "Riwayat masalah dekorasi di event sebelumnya"],
        correct_index: 1, explanation: "Delegasi yang jelas mencakup batas keputusan yang boleh diambil sendiri dan waktu lapor balik, supaya koordinator tidak ragu atau melampaui wewenang." },
      { stem: "Dua kru bertengkar soal siapa yang salah meletakkan sound system. Langkah pertama yang tepat?",
        options: ["Menentukan siapa yang salah lalu menegurnya di depan tim", "Memisahkan orang dari masalah, mendengar kedua versi, lalu menyepakati fakta", "Mengabaikan sampai event selesai", "Meminta vendor sound memutuskan"],
        correct_index: 1, explanation: "Menyelesaikan konflik dimulai dari fakta yang disepakati, bukan mencari siapa yang salah, agar keputusan lapangan bisa segera diambil." },
      { stem: "Mengapa setiap posisi kunci sebaiknya punya orang kedua yang tahu rundown?",
        options: ["Supaya biaya kru lebih besar", "Agar pemimpin tidak perlu hadir", "Supaya event tetap jalan kalau orang pertama berhalangan atau sibuk menangani masalah", "Karena klien memintanya"],
        correct_index: 2, explanation: "Kesinambungan komando adalah tanggung jawab pemimpin. Pengganti yang siap mencegah satu orang menjadi titik gagal tunggal." },
    ],
  },
  {
    slug: "pb-speak",
    title: "Public speaking: pitch, briefing, dan MC",
    curriculum_ref: "Personal Behavior 2",
    phase_id: 0, week_from: null, week_to: null, sort_order: 102,
    summary: "Seorang pemilik EO berbicara di depan klien saat pitching, di depan kru saat briefing, dan kadang memegang mikrofon sebagai MC. Topik ini melatih struktur bicara, pengelolaan gugup, dan cara menyampaikan angka atau keputusan dengan meyakinkan.",
    units: [unit("BSBCMM411"), unit("SITXMPR016")],
    university: [uni("psu", "HM 290W Hospitality Managerial Communication"), uni("ehl", "9618AS Influence & Leadership: Negotiation & Communication Tools")],
    points: [
      "Setiap presentasi punya satu pesan utama yang bisa diucapkan dalam satu kalimat. Semua slide dan cerita mendukung kalimat itu.",
      "Struktur pitch ke klien: masalah atau keinginan klien, konsep yang menjawabnya, bukti (portofolio, angka), rencana, lalu ajakan memutuskan.",
      "Gugup dikelola dengan persiapan fisik (napas, berdiri seimbang) dan latihan bersuara keras minimal tiga kali sebelum tampil.",
      "Saat menyampaikan angka, bulatkan dan bandingkan: 'sekitar 40 persen lebih hemat dari opsi pertama' lebih mudah ditangkap daripada tabel penuh.",
      "MC yang baik menguasai rundown, menyebut nama dengan benar, dan punya kalimat pengisi untuk jeda teknis.",
      "Setelah presentasi, minta satu umpan balik konkret dari pendengar dan catat untuk presentasi berikutnya.",
    ],
    evidence_brief: "Rekam video presentasi 5 sampai 7 menit saat kamu mem-pitch konsep event ke klien (boleh simulasi dengan tim). Unggah tautan video dan satu halaman catatan: pesan utama, struktur yang dipakai, dan dua hal yang ingin diperbaiki.",
    sources: [],
    questions: [
      { stem: "Apa langkah pertama saat menyusun presentasi konsep untuk klien wedding?",
        options: ["Memilih template slide", "Menentukan satu pesan utama dalam satu kalimat", "Menyiapkan daftar harga", "Mengumpulkan semua foto portofolio"],
        correct_index: 1, explanation: "Satu pesan utama memandu isi seluruh presentasi. Slide dan cerita dipilih berdasarkan apakah mendukung pesan itu." },
      { stem: "Cara paling efektif menyampaikan perbandingan biaya dua opsi dekorasi secara lisan?",
        options: ["Membacakan seluruh rincian tabel", "Menyebut angka dibulatkan dan perbandingannya, misalnya 'sekitar 40 persen lebih hemat'", "Menghindari angka sama sekali", "Mengirim spreadsheet setelah presentasi saja"],
        correct_index: 1, explanation: "Angka yang dibulatkan dan dibandingkan lebih mudah ditangkap pendengar. Rinciannya bisa dilampirkan terpisah." },
      { stem: "Mengapa MC perlu punya kalimat pengisi yang disiapkan?",
        options: ["Agar terlihat lebih pandai", "Untuk mengisi jeda teknis tanpa membuat tamu merasa ada masalah", "Supaya rundown lebih panjang", "Karena klien memintanya"],
        correct_index: 1, explanation: "Jeda teknis hampir selalu terjadi. Kalimat pengisi menjaga suasana sementara tim menyelesaikan masalah." },
    ],
  },
  {
    slug: "pb-english",
    title: "English untuk profesional event",
    curriculum_ref: "Personal Behavior 3",
    phase_id: 0, week_from: null, week_to: null, sort_order: 103,
    summary: "Klien asing, vendor internasional, dan seluruh materi acuan AQF serta modul kampus memakai bahasa Inggris. Topik ini melatih English kerja: email, proposal, rundown, dan percakapan dengan klien atau vendor.",
    units: [unit("BSBWRT411"), unit("BSBCMM411")],
    university: [uni("ehl", "7182BC Introduction to Business Communication"), uni("napier_ba", "Academic and Professional Skills")],
    points: [
      "Kuasai kosakata inti industri dulu: run of show, load-in, load-out, cue, holding room, floor plan, deposit, balance payment, scope of work.",
      "Email kerja dalam bahasa Inggris memakai pola tetap: sapaan, tujuan email dalam kalimat pertama, poin dalam daftar, permintaan tindakan dengan tenggat, penutup.",
      "Saat bicara dengan klien asing, ulangi permintaan mereka dengan kata-katamu sendiri untuk memastikan paham: 'So you would like the ceremony to start at four, correct?'",
      "Baca satu unit AQF dalam bahasa Inggris tiap minggu dan tandai istilah baru. Itu latihan membaca yang langsung berguna untuk program ini.",
      "Rundown dua bahasa membantu kru dan vendor asing bekerja dari dokumen yang sama.",
      "Tidak perlu sempurna. Kalimat pendek yang jelas lebih baik daripada kalimat panjang yang salah.",
    ],
    evidence_brief: "Tulis satu email penawaran atau konfirmasi dalam bahasa Inggris ke klien atau vendor nyata (nama boleh disamarkan) dan satu rundown event dalam versi dua bahasa. Lampirkan keduanya beserta daftar 20 istilah event yang kamu pelajari.",
    sources: [],
    questions: [
      { stem: "Kalimat pertama email kerja berbahasa Inggris sebaiknya berisi apa?",
        options: ["Basa-basi tentang cuaca", "Tujuan email secara langsung", "Riwayat hubungan kerja", "Daftar harga"],
        correct_index: 1, explanation: "Pembaca yang sibuk perlu tahu tujuan email sejak kalimat pertama. Detail menyusul dalam daftar poin." },
      { stem: "Istilah 'load-in' dalam produksi event berarti?",
        options: ["Pembayaran awal dari klien", "Proses memasukkan dan memasang peralatan ke venue", "Daftar tamu yang sudah check-in", "Sesi foto sebelum acara"],
        correct_index: 1, explanation: "Load-in adalah tahap memasukkan dan memasang peralatan; lawannya load-out saat bongkar." },
      { stem: "Klien asing menjelaskan keinginan yang rumit. Cara memastikan kamu paham?",
        options: ["Mengangguk dan lanjut ke topik berikut", "Mengulang permintaannya dengan kata-katamu sendiri lalu minta konfirmasi", "Meminta klien menulis ulang dalam bahasa Indonesia", "Menebak dari konteks"],
        correct_index: 1, explanation: "Parafrase dan konfirmasi mencegah salah paham yang mahal di hari H." },
    ],
  },
  {
    slug: "fund",
    title: "Fundamental: peta industri event",
    curriculum_ref: "Fundamental",
    phase_id: 1, week_from: 1, week_to: 1, sort_order: 1,
    summary: "Sebelum masuk teknis, kamu perlu peta: jenis event, siapa saja pemainnya, bagaimana uang mengalir, dan dari mana informasi industri yang bisa dipercaya. Minggu pertama membangun bahasa yang sama untuk 23 minggu berikutnya.",
    units: [unit("SITEEVT020")],
    university: [uni("ucf", "HFT2750 The Event Industry"), uni("napier_ba", "The Business of Festivals & Events")],
    points: [
      "Event dikelompokkan menurut tujuan: private (wedding, ulang tahun), corporate (launching, gathering, konferensi), public (festival, konser, pameran), dan sport. Tiap jenis punya pola risiko dan sumber pendapatan yang berbeda.",
      "Pemain dalam satu event: klien atau pemilik acara, organizer, venue, vendor spesialis (dekor, catering, sound, dokumentasi), pihak berwenang (izin, keamanan), dan peserta.",
      "Uang mengalir dari klien atau tiket dan sponsor ke organizer, lalu ke vendor. Margin organizer ada di selisih harga dan efisiensi koordinasi.",
      "Siklus event terdiri dari lima tahap: riset dan konsep, perencanaan, produksi, pelaksanaan, evaluasi. Setiap topik program ini berada di salah satu tahap.",
      "Informasi industri yang bisa dipercaya berasal dari standar dan unit kompetensi resmi, asosiasi, dokumen pemerintah, dan laporan venue atau vendor, bukan hanya media sosial.",
      "Tren yang harus dipantau EO: event hybrid, keberlanjutan, keselamatan kerumunan, dan teknologi registrasi.",
    ],
    evidence_brief: "Buat peta pemangku kepentingan (stakeholder map) satu halaman untuk satu event nyata yang pernah kamu tangani: siapa saja pihaknya, peran, dan arus uang di antara mereka. Tambahkan daftar lima sumber informasi industri yang akan kamu ikuti rutin.",
    sources: [],
    questions: [
      { stem: "Wedding dan launching produk termasuk kategori event yang berbeda. Perbedaan yang paling menentukan cara kerja EO?",
        options: ["Jumlah tamu", "Tujuan event dan sumber pendapatannya", "Warna dekorasi", "Durasi acara"],
        correct_index: 1, explanation: "Tujuan (private vs corporate) menentukan siapa yang membayar, ukuran keberhasilan, dan pola risikonya." },
      { stem: "Dari lima tahap siklus event, tahap mana yang paling sering dilewati EO kecil padahal menentukan pekerjaan berikutnya?",
        options: ["Riset dan konsep", "Perencanaan", "Produksi", "Evaluasi"],
        correct_index: 3, explanation: "Evaluasi sering dilewati karena tim lelah setelah hari H, padahal laporannya menjadi bahan proposal dan perbaikan event berikutnya." },
      { stem: "Sumber informasi industri mana yang paling layak dijadikan acuan saat menyusun SOP?",
        options: ["Cuplikan video event viral", "Unit kompetensi resmi dan standar industri", "Pendapat teman sesama EO", "Komentar tamu di media sosial"],
        correct_index: 1, explanation: "Unit kompetensi dan standar ditulis untuk diaudit dan dipakai lintas organisasi, jadi lebih andal untuk SOP." },
    ],
  },
  {
    slug: "pm",
    title: "Project management untuk event",
    curriculum_ref: "Official: Project Management",
    phase_id: 1, week_from: 2, week_to: 2, sort_order: 2,
    summary: "Setiap event adalah proyek: punya awal, akhir, anggaran, dan hasil yang jelas. Topik ini memberi alat dasar untuk memecah pekerjaan, mengurutkan, menjadwalkan, dan memantau kemajuannya.",
    units: [unit("SITXMGT006")],
    university: [uni("ehl", "9507AR Project Management"), uni("tio", "Project Management")],
    points: [
      "Work Breakdown Structure (WBS) memecah event menjadi paket kerja yang bisa diberikan ke satu orang: misalnya 'dekorasi pelaminan' bukan 'dekorasi'.",
      "Setiap paket kerja punya pemilik, tenggat, dan hasil yang bisa dicek (deliverable). Tanpa tiga itu, paket kerja hanya harapan.",
      "Urutan ketergantungan menentukan jalur kritis: pekerjaan yang kalau terlambat akan menggeser hari H, misalnya konfirmasi venue sebelum cetak undangan.",
      "Jadwal proyek dibaca mundur dari hari H (backward planning), lalu diberi buffer pada pekerjaan yang bergantung pada pihak luar.",
      "Rapat kemajuan mingguan cukup 15 menit dengan tiga pertanyaan: apa yang selesai, apa yang terhambat, apa yang perlu keputusan.",
      "Perubahan lingkup (scope change) dari klien dicatat tertulis dengan dampaknya ke biaya dan jadwal sebelum disetujui.",
    ],
    evidence_brief: "Susun WBS dan jadwal (Gantt sederhana boleh di spreadsheet) untuk satu event yang akan kamu kerjakan dalam tiga bulan ke depan. Tandai jalur kritis dan tulis siapa pemilik tiap paket kerja.",
    sources: [],
    questions: [
      { stem: "Mana contoh paket kerja WBS yang cukup kecil untuk diberikan ke satu orang?",
        options: ["Dekorasi", "Acara resepsi", "Pemasangan backdrop pelaminan selesai H-1 pukul 20.00", "Sukses acara"],
        correct_index: 2, explanation: "Paket kerja yang baik punya hasil konkret dan bisa dicek. 'Dekorasi' terlalu luas untuk satu pemilik." },
      { stem: "Konfirmasi venue terlambat dua minggu. Mengapa ini menggeser hari H sementara keterlambatan pemilihan souvenir tidak?",
        options: ["Venue lebih mahal", "Venue berada di jalur kritis karena banyak pekerjaan bergantung padanya", "Souvenir tidak penting", "Klien lebih peduli venue"],
        correct_index: 1, explanation: "Pekerjaan di jalur kritis punya rantai ketergantungan panjang; menundanya menunda semua yang mengikutinya." },
      { stem: "Klien meminta tambahan sesi foto outdoor seminggu sebelum acara. Tindakan yang benar?",
        options: ["Langsung mengiyakan agar klien senang", "Menolak karena sudah terlambat", "Mencatat perubahan lingkup dengan dampak biaya dan jadwal, lalu minta persetujuan tertulis", "Meminta vendor foto menanggung biayanya"],
        correct_index: 2, explanation: "Perubahan lingkup harus terdokumentasi dengan dampaknya supaya tidak menjadi sengketa saat tagihan akhir." },
    ],
  },
  {
    slug: "proposal",
    title: "Proposal dan perencanaan event",
    curriculum_ref: "Knowledge 2",
    phase_id: 1, week_from: 3, week_to: 3, sort_order: 3,
    summary: "Proposal adalah dokumen penjualan sekaligus rencana kerja awal. Yang baik menjawab kebutuhan klien dengan konsep, rencana, dan harga yang bisa dipertanggungjawabkan, lalu berkembang menjadi event plan setelah disetujui.",
    units: [unit("SITXMPR016")],
    university: [uni("surrey", "The UG Live Event Project (Event Planning & Marketing)"), uni("napier_ba", "Event Management")],
    points: [
      "Proposal dimulai dari brief klien: tujuan, tanggal, jumlah tamu, anggaran, dan hal yang tidak boleh terjadi. Tanpa brief tertulis, proposal menebak.",
      "Struktur proposal: pemahaman kebutuhan, konsep dan tema, rencana acara (rundown garis besar), lingkup pekerjaan, tim, portofolio, harga dan syarat pembayaran, jadwal keputusan.",
      "Lingkup pekerjaan (scope of work) menyebut apa yang termasuk dan yang tidak termasuk. Bagian 'tidak termasuk' mencegah perselisihan.",
      "Event plan setelah proposal disetujui memuat: tujuan terukur, timeline, anggaran rinci, daftar vendor, layout, rundown, rencana risiko, dan rencana komunikasi.",
      "Harga di proposal disusun dari anggaran (bukan sebaliknya), dengan margin dan cadangan yang jelas untuk internal.",
      "Proposal dikirim dengan tenggat berlaku (validity) supaya harga vendor yang berubah tidak merugikan.",
    ],
    evidence_brief: "Unggah satu proposal event nyata yang kamu tulis (harga boleh disamarkan) beserta brief klien yang mendasarinya. Tandai bagian lingkup pekerjaan 'termasuk' dan 'tidak termasuk'.",
    sources: [],
    questions: [
      { stem: "Apa yang harus ada sebelum kamu mulai menulis proposal?",
        options: ["Daftar vendor favorit", "Brief klien tertulis: tujuan, tanggal, tamu, anggaran, batasan", "Template desain yang bagus", "Harga kompetitor"],
        correct_index: 1, explanation: "Proposal menjawab kebutuhan. Tanpa brief tertulis, proposal berisi tebakan dan sering harus ditulis ulang." },
      { stem: "Mengapa bagian 'tidak termasuk' penting dalam lingkup pekerjaan?",
        options: ["Supaya proposal lebih panjang", "Untuk mencegah klien mengira sesuatu sudah termasuk padahal belum dianggarkan", "Karena aturan asosiasi", "Agar bisa menaikkan harga nanti"],
        correct_index: 1, explanation: "Perselisihan paling sering muncul dari asumsi klien tentang hal yang tidak pernah dianggarkan. Menuliskannya melindungi kedua pihak." },
      { stem: "Urutan yang benar saat menentukan harga di proposal?",
        options: ["Tentukan harga pasar dulu, lalu sesuaikan anggaran", "Susun anggaran rinci, tambah margin dan cadangan, baru tetapkan harga", "Ikuti harga event sebelumnya", "Tanyakan klien mau bayar berapa"],
        correct_index: 1, explanation: "Harga yang dibangun dari anggaran memastikan margin nyata; harga yang ditebak sering membuat event rugi." },
    ],
  },
  {
    slug: "bizdoc",
    title: "Dokumen bisnis: kontrak, penawaran, MoU, invoice",
    curriculum_ref: "Knowledge 12",
    phase_id: 1, week_from: 4, week_to: 4, sort_order: 4,
    summary: "Dokumen bisnis melindungi uang dan hubungan kerja. Topik ini membahas dokumen yang dipakai EO dan WO setiap hari: penawaran, kontrak klien, perjanjian vendor, MoU, invoice, berita acara, dan SOP.",
    units: [unit("BSBWRT411"), unit("SITXMGT005")],
    university: [uni("ehl", "9120IM Business Communication"), uni("psu", "HM 485 Advanced Meeting and Event Management")],
    points: [
      "Kontrak klien minimal memuat: para pihak, lingkup pekerjaan, tanggal dan tempat, harga dan jadwal pembayaran, ketentuan perubahan, pembatalan dan force majeure, tanggung jawab kerusakan, tanda tangan.",
      "Perjanjian vendor mencerminkan kontrak klien: jadwal, spesifikasi teknis, denda keterlambatan, dan syarat pembayaran yang lebih lambat dari pembayaran klien ke kamu.",
      "Invoice yang benar menyebut nomor, tanggal, rincian, pajak jika ada, jatuh tempo, dan rekening. Kirim segera setelah termin tercapai.",
      "Berita acara serah terima (setelah event) menutup pekerjaan dan menjadi dasar pembayaran akhir.",
      "MoU dipakai untuk kerja sama jangka panjang dengan venue atau vendor, mengikat prinsip kerja sama sebelum kontrak per event.",
      "Semua dokumen memakai penomoran dan versi. Simpan di satu folder per event dengan nama file yang konsisten.",
    ],
    evidence_brief: "Kumpulkan set dokumen dari satu event nyata: penawaran, kontrak klien, satu perjanjian vendor, invoice termin, dan berita acara (data sensitif disamarkan). Tambahkan checklist klausul kontrak yang kamu pakai.",
    sources: [],
    questions: [
      { stem: "Klausul kontrak mana yang paling melindungi EO saat acara batal karena banjir?",
        options: ["Klausul harga", "Klausul pembatalan dan force majeure", "Klausul tanda tangan", "Klausul lingkup pekerjaan"],
        correct_index: 1, explanation: "Klausul pembatalan dan force majeure mengatur siapa menanggung biaya yang sudah keluar saat kejadian di luar kendali." },
      { stem: "Mengapa syarat pembayaran ke vendor sebaiknya lebih lambat dari pembayaran klien ke kamu?",
        options: ["Agar vendor lebih rajin", "Supaya arus kas EO tidak menalangi biaya vendor", "Karena vendor tidak butuh uang cepat", "Tidak ada alasan khusus"],
        correct_index: 1, explanation: "Menyelaraskan termin menjaga kas: uang klien masuk dulu, baru dibayarkan ke vendor." },
      { stem: "Dokumen apa yang menjadi dasar penagihan pembayaran akhir setelah event selesai?",
        options: ["Proposal", "Berita acara serah terima", "MoU", "Rundown"],
        correct_index: 1, explanation: "Berita acara menyatakan pekerjaan selesai diterima klien, sehingga invoice akhir punya dasar yang jelas." },
    ],
  },
];
