import { unit } from "./units.mjs";
import { uni } from "./universities.mjs";

// Fase 4 (Keselamatan), Fase 5 (Komersial & Kreatif), Fase 6 (Orang & Hasil)
export const TOPICS_C = [
  {
    slug: "risk",
    title: "Risk management: penilaian risiko dan rencana darurat",
    curriculum_ref: "Knowledge 11",
    phase_id: 4, week_from: 14, week_to: 14, sort_order: 13,
    summary: "Setiap event punya risiko yang bisa diperkirakan. Topik ini melatih mengidentifikasi bahaya, menilai kemungkinan dan dampak, menetapkan pengendalian, dan menyusun rencana darurat yang benar-benar bisa dijalankan kru.",
    units: [unit("SITXWHS006"), unit("SITXWHS007")],
    university: [uni("ucf", "HFT3670 Hospitality and Event Risk Management"), uni("surrey", "Crisis Management")],
    points: [
      "Proses penilaian risiko: identifikasi bahaya, nilai kemungkinan dan dampak (matriks 1 sampai 5), tentukan pengendalian, tetapkan pemilik, tinjau ulang setelah perubahan.",
      "Hierarki pengendalian dari yang paling kuat: hilangkan bahaya, ganti dengan yang lebih aman, pengendalian teknis (pagar, ramp kabel), pengendalian administratif (SOP, briefing), alat pelindung diri.",
      "Bahaya khas event: listrik dan kabel, struktur (panggung, truss, tenda), kebakaran dan kembang api, cuaca, makanan, kerumunan, lalu lintas kendaraan saat loading.",
      "Rencana darurat memuat: titik kumpul, jalur evakuasi, nomor darurat, siapa yang memutuskan evakuasi, cara mengumumkan ke tamu, dan lokasi P3K serta APAR.",
      "Kru dibriefing tentang rencana darurat sebelum pintu dibuka; kru kunci tahu posisi APAR dan jalur evakuasi terdekat dari posnya.",
      "Insiden sekecil apa pun dicatat (near miss termasuk) dan ditinjau setelah event untuk memperbaiki pengendalian.",
    ],
    evidence_brief: "Unggah dokumen penilaian risiko satu event nyata (tabel bahaya, kemungkinan, dampak, pengendalian, pemilik) dan rencana daruratnya (titik kumpul, jalur evakuasi di floor plan, nomor darurat, pengambil keputusan).",
    sources: [],
    questions: [
      { stem: "Kabel sound melintang di jalur tamu. Pengendalian mana yang paling kuat menurut hierarki pengendalian?",
        options: ["Memasang tanda 'hati-hati kabel'", "Mengubah jalur kabel agar tidak melintasi jalur tamu", "Meminta kru mengingatkan tamu", "Memberi kru sepatu safety"],
        correct_index: 1, explanation: "Menghilangkan bahaya (kabel tidak melintasi jalur tamu) berada di puncak hierarki; tanda dan pengingat adalah pengendalian administratif yang lebih lemah." },
      { stem: "Apa yang membuat rencana darurat bisa dijalankan, bukan sekadar dokumen?",
        options: ["Ditulis dalam bahasa Inggris", "Kru dibriefing sebelum pintu dibuka dan tahu peran, jalur, dan titik kumpul", "Ditandatangani klien", "Dicetak berwarna"],
        correct_index: 1, explanation: "Rencana hanya bekerja jika orang di lapangan tahu apa yang harus dilakukan tanpa membaca dokumen saat darurat." },
      { stem: "Mengapa near miss (hampir celaka) tetap harus dicatat?",
        options: ["Untuk menyalahkan vendor", "Karena near miss menunjukkan pengendalian yang gagal sebelum ada korban", "Untuk laporan pajak", "Tidak perlu dicatat"],
        correct_index: 1, explanation: "Near miss adalah peringatan gratis. Menindaklanjutinya mencegah insiden yang sama berulang dengan akibat lebih berat." },
    ],
  },
  {
    slug: "crowd",
    title: "Crowd management: alur tamu, kapasitas, dan keamanan",
    curriculum_ref: "Knowledge 15",
    phase_id: 4, week_from: 15, week_to: 15, sort_order: 14,
    summary: "Kerumunan yang tidak dikelola adalah risiko terbesar event publik dan juga wedding besar. Topik ini membahas perhitungan kapasitas, desain alur masuk dan keluar, penempatan petugas, dan koordinasi dengan keamanan.",
    units: [unit("SITEEVT034")],
    university: [uni("surrey", "Crisis Management"), uni("ucf", "HFT3670 Hospitality and Event Risk Management")],
    points: [
      "Kapasitas aman dihitung dari luas area yang bisa dipakai, lebar dan jumlah pintu keluar, serta waktu evakuasi, bukan dari jumlah undangan yang diinginkan klien.",
      "Tiga fase kerumunan: masuk (ingress), selama acara (circulation), keluar (egress). Antrean masuk dan momen keluar serentak adalah titik paling rawan.",
      "Alur masuk didesain agar registrasi tidak menjadi sumbatan: jumlah meja registrasi sesuai laju kedatangan, jalur tamu VIP terpisah, area tunggu yang teduh.",
      "Kepadatan dipantau di titik kritis (depan panggung, pintu, tangga). Pada kepadatan tinggi petugas menghentikan aliran masuk ke area itu.",
      "Petugas keamanan dan kru diberi posisi, tugas, dan kata sandi radio. Untuk event besar, koordinasi dengan kepolisian dan pengelola venue dilakukan sebelum hari H.",
      "Rencana kerumunan ditulis singkat: peta alur, kapasitas per area, posisi petugas, pemicu tindakan (misalnya menutup pintu), dan pengumuman yang disiapkan.",
    ],
    evidence_brief: "Buat rencana crowd management untuk satu event nyata: peta alur masuk dan keluar di floor plan, perhitungan kapasitas per area, posisi petugas, dan daftar pemicu tindakan. Unggah beserta foto kondisi antrean saat event (jika ada).",
    sources: [],
    questions: [
      { stem: "Dasar yang benar untuk menentukan kapasitas maksimum sebuah area?",
        options: ["Jumlah undangan yang dicetak", "Luas area yang bisa dipakai, pintu keluar, dan waktu evakuasi", "Jumlah kursi yang tersedia di gudang", "Permintaan klien"],
        correct_index: 1, explanation: "Kapasitas adalah soal keselamatan: berapa orang yang bisa keluar dengan aman dalam waktu tertentu." },
      { stem: "Fase kerumunan mana yang biasanya paling rawan?",
        options: ["Saat makan", "Masuk dan keluar serentak (ingress dan egress)", "Saat sambutan", "Saat foto bersama"],
        correct_index: 1, explanation: "Ingress dan egress memusatkan banyak orang di pintu dalam waktu singkat sehingga kepadatan melonjak." },
      { stem: "Kepadatan di depan panggung sudah sangat tinggi. Tindakan petugas yang tepat?",
        options: ["Membiarkan karena acara hampir selesai", "Menghentikan aliran masuk ke area itu dan membuka jalur keluar", "Meminta tamu berdiri lebih rapat", "Mematikan lampu"],
        correct_index: 1, explanation: "Menutup aliran masuk ke titik padat dan membuka jalur keluar menurunkan kepadatan tanpa memicu kepanikan." },
    ],
  },
  {
    slug: "legal",
    title: "Perizinan, hukum, dan kepatuhan",
    curriculum_ref: "Tambahan (tidak ada di kurikulum Enter Event House)",
    phase_id: 4, week_from: 16, week_to: 16, sort_order: 15,
    summary: "Topik tambahan dari acuan AQF yang tidak ada di kurikulum asli: izin keramaian, hak cipta musik, asuransi, dan kewajiban hukum lain yang sering terlewat oleh EO kecil. Diletakkan di fase keselamatan karena akibatnya sama seriusnya.",
    units: [unit("SITXGLC002")],
    university: [uni("napier_ba", "Planning and Public Policy for Festival & Events"), uni("psu", "HM 355 Legal Aspects of the Hospitality Industry")],
    points: [
      "Buat daftar kepatuhan per jenis event: izin keramaian ke kepolisian untuk acara publik, pemberitahuan ke pengelola kawasan, izin penggunaan ruang publik, dan aturan venue.",
      "Musik yang diputar atau dimainkan di acara komersial punya konsekuensi royalti; cek kewajiban lisensi ke lembaga manajemen kolektif yang berlaku dan siapa (venue atau organizer) yang menanggungnya.",
      "Asuransi event (public liability) melindungi dari tuntutan pihak ketiga atas cedera atau kerusakan; tanyakan juga asuransi vendor untuk alat berat dan rigging.",
      "Data pribadi tamu (daftar hadir, nomor telepon) dikumpulkan seperlunya, disimpan aman, dan tidak dibagikan ke vendor tanpa perlu.",
      "Kewajiban ketenagakerjaan untuk kru harian: perjanjian kerja singkat, upah sesuai kesepakatan, jam kerja wajar, dan perlindungan kecelakaan kerja.",
      "Semua izin dan polis disimpan di production book dan salinannya dibawa ke lokasi pada hari H.",
    ],
    evidence_brief: "Susun checklist kepatuhan untuk satu event nyata (izin, lisensi musik, asuransi, data tamu, kru) beserta status tiap butir dan dokumen buktinya (salinan izin atau korespondensi, data sensitif disamarkan).",
    sources: [],
    questions: [
      { stem: "Konser komunitas di lapangan terbuka dengan 2.000 penonton. Izin apa yang paling mendasar?",
        options: ["Izin dari vendor sound", "Izin keramaian dari kepolisian dan izin penggunaan ruang publik", "Izin dari sponsor", "Tidak perlu izin"],
        correct_index: 1, explanation: "Acara publik di ruang terbuka memerlukan izin keramaian dan izin pemakaian lokasi dari pihak berwenang." },
      { stem: "Apa yang dilindungi oleh asuransi public liability?",
        options: ["Kerugian jika klien tidak membayar", "Tuntutan pihak ketiga atas cedera atau kerusakan yang terjadi di event", "Kerusakan alat vendor", "Biaya pemasaran"],
        correct_index: 1, explanation: "Public liability menanggung klaim dari pihak ketiga, misalnya tamu yang terluka karena struktur yang roboh." },
      { stem: "Vendor dokumentasi meminta seluruh daftar tamu beserta nomor telepon. Respons yang benar?",
        options: ["Berikan semuanya agar mudah", "Berikan hanya data yang benar-benar diperlukan untuk tugasnya", "Tolak semua komunikasi", "Unggah daftar ke grup vendor"],
        correct_index: 1, explanation: "Data pribadi dibagikan seperlunya. Nomor telepon tamu jarang diperlukan vendor dokumentasi." },
    ],
  },
  {
    slug: "concept",
    title: "Creative concept development: dari brief menjadi pengalaman",
    curriculum_ref: "Knowledge 1",
    phase_id: 5, week_from: 17, week_to: 18, sort_order: 16,
    summary: "Konsep yang kuat lahir dari brief yang dipahami, bukan dari tren. Dua minggu ini melatih cara menggali cerita klien, menyusun tema, merancang pengalaman tamu dari datang sampai pulang, dan menjaga konsep tetap bisa diproduksi dan dibayar.",
    units: [unit("SITXMPR016"), unit("SITEEVT020")],
    university: [uni("tio", "Creative Concept Design"), uni("napier_msc", "Experience Design and Management for Tourism, Hospitality and Events")],
    points: [
      "Konsep dimulai dari pertanyaan ke klien: apa yang ingin tamu rasakan, cerita apa yang ingin diceritakan, apa yang tidak boleh terjadi. Jawabannya menjadi 'kalimat konsep' satu baris.",
      "Tema diturunkan menjadi elemen konkret: palet warna, material, musik, pencahayaan, tata ruang, dan momen kunci (grand entrance, first dance, penyerahan simbolis).",
      "Perjalanan tamu (guest journey) dipetakan dari undangan, tiba, registrasi, area utama, makan, hiburan, sampai pulang. Tiap titik punya satu hal yang dirancang.",
      "Moodboard dan sketsa layout dibuat sebelum rendering mahal; setujui arah dulu, detail kemudian.",
      "Setiap ide kreatif dicek tiga hal: bisa diproduksi di venue itu, masuk anggaran, dan aman. Ide yang gagal salah satunya diubah, bukan dipaksakan.",
      "Presentasi konsep memakai cerita: mulai dari perasaan yang ingin dicapai, lalu tunjukkan bagaimana tiap elemen mendukungnya.",
    ],
    evidence_brief: "Unggah dokumen konsep satu event nyata: kalimat konsep, moodboard, peta perjalanan tamu, daftar elemen tema, dan catatan uji 'bisa diproduksi, masuk anggaran, aman' untuk tiga ide utama.",
    sources: [],
    questions: [
      { stem: "Sumber terbaik untuk kalimat konsep sebuah wedding?",
        options: ["Tren dekorasi tahun ini", "Jawaban klien tentang apa yang ingin dirasakan tamu dan cerita yang ingin diceritakan", "Portofolio EO lain", "Ketersediaan vendor"],
        correct_index: 1, explanation: "Konsep yang bermakna bagi klien berasal dari cerita mereka; tren hanya alat bantu eksekusi." },
      { stem: "Apa manfaat memetakan perjalanan tamu dari undangan sampai pulang?",
        options: ["Supaya proposal lebih tebal", "Memastikan setiap titik sentuh dirancang, bukan hanya area utama", "Untuk menghitung biaya parkir", "Tidak ada manfaat"],
        correct_index: 1, explanation: "Pengalaman tamu terbentuk dari seluruh perjalanan; titik yang tidak dirancang (parkir, antrean) sering merusak kesan." },
      { stem: "Ide instalasi lampu gantung besar lolos anggaran tapi venue tidak punya titik gantung yang kuat. Keputusan yang benar?",
        options: ["Paksakan dengan struktur seadanya", "Ubah ide menjadi versi yang bisa diproduksi dengan aman di venue itu", "Batalkan seluruh konsep", "Minta klien pindah venue"],
        correct_index: 1, explanation: "Uji 'bisa diproduksi, masuk anggaran, aman' gagal di keamanan; idenya diubah, bukan dipaksakan." },
    ],
  },
  {
    slug: "mkt",
    title: "Marketing dan promosi event",
    curriculum_ref: "Knowledge 6",
    phase_id: 5, week_from: 19, week_to: 19, sort_order: 17,
    summary: "Ada dua pemasaran dalam bisnis event: memasarkan event ke pesertanya (untuk event publik) dan memasarkan jasa EO ke calon klien. Topik ini membahas keduanya, termasuk sponsorship sebagai sumber dana.",
    units: [unit("SITXMPR012"), unit("SITXMPR015")],
    university: [uni("ucf", "HFT3512 Event Promotion"), uni("napier_ba", "Digital Services Marketing")],
    points: [
      "Rencana pemasaran satu halaman: target audiens, pesan utama, saluran, jadwal, anggaran, dan ukuran keberhasilan (pendaftar, tiket terjual, prospek masuk).",
      "Untuk event publik, timeline promosi mundur dari hari H: pengumuman, early bird, konten pengisi acara, pengingat terakhir. Penjualan tiket biasanya menumpuk di akhir.",
      "Untuk jasa EO dan WO, portofolio adalah alat pemasaran utama: dokumentasi yang rapi, testimoni, dan studi kasus singkat (masalah, solusi, hasil).",
      "Sponsorship dijual sebagai akses ke audiens tertentu, bukan sebagai permintaan bantuan. Proposal sponsor memuat profil audiens, paket manfaat, dan harga.",
      "Kemitraan dengan venue dan vendor (saling merekomendasikan) sering lebih murah dan lebih efektif daripada iklan.",
      "Ukur tiap saluran: dari mana prospek atau pendaftar datang, lalu pindahkan anggaran ke saluran yang terbukti.",
    ],
    evidence_brief: "Unggah rencana pemasaran satu halaman untuk event nyata atau untuk jasa EO-mu, beserta satu studi kasus portofolio (masalah, solusi, hasil, foto) dan, jika ada, satu proposal sponsor yang pernah dikirim.",
    sources: [],
    questions: [
      { stem: "Cara yang benar menawarkan sponsorship ke sebuah merek?",
        options: ["Meminta bantuan dana karena anggaran kurang", "Menawarkan akses ke audiens tertentu dengan paket manfaat dan harga yang jelas", "Mengirim rundown acara", "Menjanjikan logo di semua tempat tanpa rincian"],
        correct_index: 1, explanation: "Sponsor membeli akses ke audiens dan manfaat terukur, bukan menyumbang." },
      { stem: "Apa alat pemasaran paling penting bagi jasa WO?",
        options: ["Iklan koran", "Portofolio dengan dokumentasi rapi, testimoni, dan studi kasus", "Kartu nama", "Diskon besar"],
        correct_index: 1, explanation: "Calon klien memutuskan berdasarkan bukti hasil kerja yang bisa mereka lihat." },
      { stem: "Mengapa sumber tiap prospek atau pendaftar perlu dicatat?",
        options: ["Untuk laporan pajak", "Agar anggaran promosi bisa dipindahkan ke saluran yang terbukti menghasilkan", "Supaya data lengkap", "Tidak perlu dicatat"],
        correct_index: 1, explanation: "Tanpa pengukuran per saluran, anggaran promosi terbuang ke saluran yang tidak menghasilkan." },
    ],
  },
  {
    slug: "reg",
    title: "Event registration: pendaftaran, tiket, dan check-in",
    curriculum_ref: "Knowledge 10",
    phase_id: 5, week_from: 20, week_to: 20, sort_order: 18,
    summary: "Registrasi adalah kesan pertama tamu dan sumber data event. Topik ini membahas desain alur pendaftaran, pilihan sistem (formulir, tiket digital, QR), persiapan materi, dan pelaksanaan check-in di lokasi.",
    units: [unit("SITEEVT021")],
    university: [uni("ucf", "HFT3443 Event Technology"), uni("dmu", "Running and Promoting a Venue")],
    points: [
      "Tentukan data yang benar-benar diperlukan dari peserta; formulir pendek meningkatkan penyelesaian pendaftaran.",
      "Sistem registrasi dipilih sesuai skala: spreadsheet dan formulir daring untuk acara kecil, platform tiket dengan QR untuk acara berbayar atau ribuan peserta.",
      "Konfirmasi otomatis berisi tanggal, lokasi, cara masuk, dan kode atau QR. Kirim pengingat H-3 dan H-1.",
      "Check-in di lokasi: jumlah meja sesuai laju kedatangan, jalur terpisah untuk yang sudah daftar, tamu VIP, dan pendaftaran di tempat; cadangan daftar cetak jika sistem mati.",
      "Kru registrasi dilatih untuk kasus umum: nama tidak ditemukan, tamu tambahan, pembayaran di tempat, dan cara eskalasi.",
      "Data kehadiran (jam datang, jumlah hadir vs daftar) dilaporkan setelah acara untuk evaluasi dan promosi berikutnya.",
    ],
    evidence_brief: "Unggah desain alur registrasi satu event nyata (formulir, konfirmasi, pengingat), layout meja check-in di floor plan, panduan kru registrasi, dan laporan kehadiran (hadir vs daftar, per jam).",
    sources: [],
    questions: [
      { stem: "Mengapa formulir pendaftaran sebaiknya hanya meminta data yang benar-benar diperlukan?",
        options: ["Supaya hemat kertas", "Karena formulir panjang menurunkan jumlah yang menyelesaikan pendaftaran dan menambah risiko data pribadi", "Karena aturan platform", "Tidak ada alasan"],
        correct_index: 1, explanation: "Setiap kolom tambahan mengurangi penyelesaian dan menambah data yang harus dijaga." },
      { stem: "Sistem registrasi mati saat check-in berlangsung. Persiapan apa yang menyelamatkan situasi?",
        options: ["Meminta tamu menunggu", "Daftar cetak cadangan dan prosedur manual yang sudah dilatih ke kru", "Menutup registrasi", "Menghubungi vendor sistem"],
        correct_index: 1, explanation: "Cadangan manual yang disiapkan sebelumnya membuat antrean tetap bergerak saat sistem gagal." },
      { stem: "Data apa dari registrasi yang paling berguna untuk evaluasi dan promosi berikutnya?",
        options: ["Warna baju tamu", "Hadir vs daftar dan pola jam kedatangan", "Nomor kursi", "Jumlah kru"],
        correct_index: 1, explanation: "Tingkat kehadiran dan pola kedatangan memperbaiki perkiraan catering, jadwal, dan strategi promosi." },
    ],
  },
  {
    slug: "team",
    title: "Team management: kru, vendor, dan relawan",
    curriculum_ref: "Knowledge 5",
    phase_id: 6, week_from: 21, week_to: 22, sort_order: 19,
    summary: "Event dikerjakan oleh orang: tim inti, kru harian, vendor, dan kadang relawan. Dua minggu ini membahas cara merekrut, membagi peran, membriefing, memantau kinerja, dan menjaga orang baik tetap mau bekerja bersamamu.",
    units: [unit("SITXHRM009"), unit("SITXHRM010"), unit("SITXHRM011"), unit("SITXHRM012")],
    university: [uni("psu", "HM 265W Teams and Leadership in the Hospitality Industry"), uni("surrey", "Managing Organisations and Human Resources")],
    points: [
      "Struktur tim per event ditulis dalam bagan: show director, koordinator area, kru per area, dan vendor dengan PIC-nya. Setiap orang tahu lapor ke siapa.",
      "Rekrutmen kru harian memakai kriteria tertulis (pengalaman, fisik, sikap) dan induksi singkat: aturan kerja, keselamatan, jam, upah, dan kontak.",
      "Deskripsi tugas per posisi satu halaman: tanggung jawab, jam, area, alat yang dipegang, dan ukuran 'selesai'.",
      "Relawan dikelola seperti kru berbayar dalam hal briefing dan keselamatan, ditambah penghargaan yang jelas: makan, sertifikat, pengalaman yang bisa ditulis.",
      "Kinerja dipantau selama event lewat koordinator area dan dievaluasi singkat setelah acara; umpan balik disampaikan pribadi, penghargaan disampaikan terbuka.",
      "Bangun daftar kru andalan: catat siapa yang bisa diandalkan untuk posisi apa, dan hubungi mereka lebih dulu untuk event berikutnya.",
    ],
    evidence_brief: "Unggah bagan tim satu event nyata, deskripsi tugas untuk tiga posisi, materi induksi kru, dan lembar evaluasi kinerja kru yang kamu isi setelah event (nama boleh disamarkan).",
    sources: [],
    questions: [
      { stem: "Apa isi minimum induksi kru harian sebelum event?",
        options: ["Sejarah perusahaan", "Aturan kerja, keselamatan, jam, upah, dan kontak", "Daftar klien", "Tema dekorasi"],
        correct_index: 1, explanation: "Induksi memastikan kru tahu cara bekerja aman dan apa haknya sebelum mulai." },
      { stem: "Cara yang tepat menyampaikan umpan balik ke kru yang melakukan kesalahan di hari H?",
        options: ["Di depan tim agar semua belajar", "Secara pribadi, spesifik pada perilaku, dampak, dan perubahan yang diminta", "Lewat pesan grup", "Tidak perlu, cukup tidak dipanggil lagi"],
        correct_index: 1, explanation: "Umpan balik pribadi dan spesifik memperbaiki perilaku tanpa mempermalukan; penghargaan justru disampaikan terbuka." },
      { stem: "Mengapa relawan tetap harus mendapat briefing keselamatan yang sama dengan kru berbayar?",
        options: ["Karena mereka meminta", "Karena risiko di lokasi tidak membedakan status pekerja, dan tanggung jawab hukum tetap pada organizer", "Supaya mereka merasa dihargai", "Tidak perlu, mereka hanya membantu"],
        correct_index: 1, explanation: "Keselamatan berlaku untuk semua orang di lokasi; organizer bertanggung jawab atas relawan seperti atas kru." },
    ],
  },
  {
    slug: "eval",
    title: "Report dan evaluasi event",
    curriculum_ref: "Knowledge 16",
    phase_id: 6, week_from: 23, week_to: 24, sort_order: 20,
    summary: "Laporan event menutup siklus dan membuka event berikutnya. Dua minggu terakhir menyusun laporan pascaevent yang lengkap: pencapaian tujuan, keuangan, operasional, insiden, umpan balik, dan rekomendasi, dalam format yang bisa dibawa ke uji kompetensi.",
    units: [unit("SITEEVT028"), unit("BSBFIN401")],
    university: [uni("ulster", "Event Delivery and Evaluation"), uni("napier_ba", "Festival & Event Impacts and Sustainability")],
    points: [
      "Evaluasi dimulai dari tujuan yang ditetapkan di awal: apakah tercapai, diukur dengan angka yang sama (jumlah hadir, kepuasan, penjualan, liputan).",
      "Struktur laporan pascaevent: ringkasan, tujuan dan hasil, keuangan (anggaran vs realisasi), operasional (jadwal rencana vs nyata), insiden dan risiko, umpan balik klien dan tamu, rekomendasi.",
      "Kumpulkan umpan balik dalam 48 jam: survei singkat ke tamu atau peserta, wawancara klien, dan debrief kru 30 menit dengan tiga pertanyaan (apa yang berjalan baik, apa yang tidak, apa yang diubah).",
      "Laporan keuangan event sederhana memakai format yang sama tiap event supaya bisa dibandingkan antarwaktu.",
      "Rekomendasi ditulis sebagai tindakan konkret dengan pemilik dan tenggat, bukan daftar keluhan.",
      "Laporan yang rapi menjadi bagian portofolio: bukti bahwa kamu merencanakan, menjalankan, dan menilai event secara profesional.",
    ],
    evidence_brief: "Susun laporan pascaevent lengkap untuk satu event nyata mengikuti struktur di inti materi, termasuk hasil survei atau umpan balik dan rekomendasi dengan pemilik dan tenggat. Ini dokumen penutup portofolio uji kompetensi.",
    sources: [],
    questions: [
      { stem: "Dasar yang benar untuk menilai keberhasilan event dalam laporan?",
        options: ["Kesan pribadi koordinator", "Tujuan yang ditetapkan di awal, diukur dengan angka yang sama", "Jumlah foto yang diunggah", "Pujian dari vendor"],
        correct_index: 1, explanation: "Evaluasi yang jujur membandingkan hasil dengan tujuan awal memakai ukuran yang sama." },
      { stem: "Mengapa umpan balik dikumpulkan dalam 48 jam setelah event?",
        options: ["Karena aturan asosiasi", "Karena ingatan tamu dan kru masih segar sehingga masukannya lebih akurat", "Supaya laporan cepat selesai", "Tidak ada alasan khusus"],
        correct_index: 1, explanation: "Detail cepat hilang dari ingatan; umpan balik yang dikumpulkan cepat lebih spesifik dan berguna." },
      { stem: "Bentuk rekomendasi yang paling berguna dalam laporan pascaevent?",
        options: ["'Registrasi harus lebih baik'", "'Tambah dua meja registrasi dan cadangan daftar cetak, pemilik: koordinator tamu, sebelum event berikutnya'", "'Semua vendor harus profesional'", "'Perlu evaluasi lebih lanjut'"],
        correct_index: 1, explanation: "Rekomendasi konkret dengan pemilik dan tenggat bisa dijalankan dan dicek pada event berikutnya." },
    ],
  },
];
